/* GENERATED by scripts/build-kits.mjs from ui_kits/app-dark/boot.jsx — do not edit. */
(function () {
/* Dark twin of ui_kits/app/index.html — same screens, same nav, same routes.
   Only the theme scope, the favicon and the white logo lockup differ; keep the
   bootstrap below in step with the light kit when routes change. */
const LOGOROOT = "../../assets/logos";
const ICONROOT = "../../assets/icons";
const {
  Avatar,
  Badge
} = window.AlfredAIDesignSystem_1ce241;
const NAV = [{
  id: "home",
  glyph: "home",
  label: "Home",
  section: "Today"
}, {
  id: "briefing",
  glyph: "briefing",
  label: "Daily briefing",
  section: "Today"
}, {
  id: "alerts",
  glyph: "alerts",
  label: "Decision alerts",
  badge: "3",
  section: "Today"
}, {
  id: "ask",
  glyph: "ask",
  label: "Ask Alfred",
  section: "Today"
}, {
  id: "cockpit",
  glyph: "cockpit",
  label: "KPI cockpit",
  section: "Intelligence"
}, {
  id: "spend",
  glyph: "spend",
  label: "Spend & ROI",
  section: "Intelligence"
}, {
  id: "creative",
  glyph: "creative",
  label: "Creative",
  section: "Intelligence"
}, {
  id: "visibility",
  glyph: "visibility",
  label: "AI visibility",
  section: "Intelligence"
}, {
  id: "integrations",
  glyph: "integrations",
  label: "Integrations",
  section: "Data"
}, {
  id: "connections",
  glyph: "integrations",
  label: "Connect data",
  section: "Data"
}, {
  id: "health",
  glyph: "visibility",
  label: "Connection health",
  section: "Data"
}, {
  id: "notifications",
  glyph: "inbox",
  label: "Notifications",
  badge: "2",
  section: "Workspace"
}, {
  id: "memory",
  glyph: "memory",
  label: "Memory",
  section: "Workspace"
}, {
  id: "team",
  glyph: "settings",
  label: "Team",
  section: "Workspace"
}, {
  id: "billing",
  glyph: "spend",
  label: "Billing",
  section: "Workspace"
}, {
  id: "audit",
  glyph: "search",
  label: "Audit log",
  section: "Workspace"
}, {
  id: "settings",
  glyph: "settings",
  label: "Settings",
  section: "Workspace"
}];
function Bell({
  onClick
}) {
  return /*#__PURE__*/React.createElement("button", {
    onClick: onClick,
    "aria-label": "Open decision alerts",
    title: "Open decision alerts",
    style: {
      position: "relative",
      width: 42,
      height: 42,
      borderRadius: "50%",
      border: "1px solid var(--border-subtle)",
      background: "var(--surface-card)",
      cursor: "pointer",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      color: "var(--text-secondary)"
    }
  }, /*#__PURE__*/React.createElement(window.NavGlyph, {
    d: window.AppGlyphs.alerts,
    size: 19
  }), /*#__PURE__*/React.createElement("span", {
    style: {
      position: "absolute",
      top: 8,
      right: 9,
      width: 9,
      height: 9,
      borderRadius: "50%",
      background: "var(--orange-500)",
      border: "2px solid var(--surface-card)"
    }
  }));
}

/* Every screen is a (navigate) => element factory — `navigate` is the app's
   setActive, so screens can deep-link into routes that aren't in the nav. */
const SCREENS = {
  home: () => /*#__PURE__*/React.createElement(window.Dashboard, null),
  briefing: () => /*#__PURE__*/React.createElement(window.DailyBrief, null),
  ask: () => /*#__PURE__*/React.createElement(window.SeekAlfred, null),
  cockpit: () => /*#__PURE__*/React.createElement(window.KpiCockpit, null),
  spend: () => /*#__PURE__*/React.createElement(window.SpendRoi, null),
  alerts: () => /*#__PURE__*/React.createElement(window.AlertsInbox, null),
  creative: () => /*#__PURE__*/React.createElement(window.CreativeLifecycle, null),
  visibility: () => /*#__PURE__*/React.createElement(window.AiVisibility, null),
  integrations: () => /*#__PURE__*/React.createElement(window.Integrations, null),
  notifications: navigate => /*#__PURE__*/React.createElement(window.NotificationsCenter, {
    onOpenAlert: () => navigate("alert-detail")
  }),
  memory: () => /*#__PURE__*/React.createElement(window.MemoryCore, null),
  connections: () => /*#__PURE__*/React.createElement(window.ConnectionFlow, null),
  health: () => /*#__PURE__*/React.createElement(window.ConnectionHealth, null),
  team: () => /*#__PURE__*/React.createElement(window.TeamPermissions, null),
  billing: () => /*#__PURE__*/React.createElement(window.BillingPlans, null),
  audit: () => /*#__PURE__*/React.createElement(window.AuditLog, null),
  settings: () => /*#__PURE__*/React.createElement(window.SettingsScreen, null),
  profile: () => /*#__PURE__*/React.createElement(window.SettingsProfile, null),
  // reached from the header avatar
  "alert-detail": () => /*#__PURE__*/React.createElement(window.AlertDetail, null),
  // reached from Notifications → "Open alert"
  "first-run": () => /*#__PURE__*/React.createElement(window.FirstRunWaiting, null) // route-only: reached from onboarding, not the nav
};
function App() {
  const [authed, setAuthed] = React.useState(false);
  const [active, setActive] = React.useState("home");
  if (!authed) return /*#__PURE__*/React.createElement(window.AuthScreen, {
    onSignedIn: () => setAuthed(true)
  });
  const titles = {
    home: ["Home", "Tuesday, 11 June · Northwind Labs"],
    briefing: ["Daily briefing", "What changed, why, and what to do"],
    ask: ["Ask Alfred", "Ask anything — answered from your data"],
    cockpit: ["KPI cockpit", "All metrics, one source of truth"],
    spend: ["Spend & ROI", "Where every dollar is working"],
    alerts: ["Decision alerts", "What needs your attention now"],
    creative: ["Creative lifecycle", "Fatigue, caught before the metrics show it"],
    visibility: ["AI visibility", "Whether AI recommends you — and what to fix"],
    integrations: ["Integrations", "Connect your marketing stack"],
    notifications: ["Notifications", "Briefs, alerts and approvals — in one inbox"],
    memory: ["Memory", "Everything I've learned about your org"],
    connections: ["Connect your data", "Read-only by default, first sync in minutes"],
    health: ["Connection health", "Every source, its freshness and status"],
    team: ["Team & permissions", "Seats, roles and invites"],
    billing: ["Billing & plans", "Your plan, usage and invoices"],
    audit: ["Audit log", "Every action — mine and yours — on the record"],
    settings: ["Settings", "Workspace & team"],
    profile: ["Profile", "You and your preferences"],
    "alert-detail": ["Decision alert", "What changed, why, and what I recommend"],
    "first-run": ["Preparing your first brief", "I'm learning your baseline now"]
  };
  const [title, subtitle] = titles[active] || titles.home;
  return /*#__PURE__*/React.createElement(window.AppShell, {
    nav: NAV,
    active: active,
    onNav: setActive,
    title: title,
    subtitle: subtitle,
    logoRoot: LOGOROOT,
    iconRoot: ICONROOT,
    logoTone: "white",
    headerRight: /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement(Bell, {
      onClick: () => setActive("alerts")
    }), /*#__PURE__*/React.createElement("button", {
      "aria-label": "Your profile",
      title: "Your profile",
      onClick: () => setActive("profile"),
      style: {
        padding: 0,
        border: "none",
        background: "transparent",
        borderRadius: "50%",
        cursor: "pointer",
        display: "inline-flex",
        lineHeight: 0
      }
    }, /*#__PURE__*/React.createElement(Avatar, {
      name: "Priya Menon",
      size: 42
    })))
  }, (SCREENS[active] || SCREENS.home)(setActive));
}
ReactDOM.createRoot(document.getElementById("root")).render(/*#__PURE__*/React.createElement(App, null));

/* function declarations, global as they were under the browser compiler */
window.Bell = Bell;
window.App = App;
})();
