/* GENERATED by scripts/build-kits.mjs from ui_kits/onboarding/boot.jsx — do not edit. */
(function () {
ReactDOM.createRoot(document.getElementById("root")).render(/*#__PURE__*/React.createElement(window.OnboardingFlow, null));
})();
