/* GENERATED by scripts/build-kits.mjs from ui_kits/app/Dashboard.jsx — do not edit. */
(function () {
const {
  Card,
  KpiCard,
  DecisionAlert,
  Badge,
  Button,
  IconButton,
  Avatar
} = window.AlfredAIDesignSystem_1ce241;
const IR = "../../assets/icons";
function Briefing() {
  return /*#__PURE__*/React.createElement(Card, {
    tone: "ink",
    radius: "var(--radius-2xl)",
    padding: 28,
    style: {
      position: "relative",
      overflow: "hidden"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      position: "absolute",
      inset: 0,
      background: "var(--glow-orange)",
      opacity: 0.6
    }
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      position: "relative",
      display: "flex",
      gap: 24,
      alignItems: "flex-start"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      width: 52,
      height: 52,
      borderRadius: "var(--radius-lg)",
      flex: "none",
      background: "var(--gradient-brand)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center"
    }
  }, /*#__PURE__*/React.createElement("img", {
    src: "../../assets/logos/alfred-icon-white.svg",
    alt: "",
    style: {
      height: 28
    }
  })), /*#__PURE__*/React.createElement("div", {
    style: {
      flex: 1
    }
  }, /*#__PURE__*/React.createElement(Badge, {
    tone: "brand",
    dot: true
  }, "Daily briefing \xB7 8:00 AM"), /*#__PURE__*/React.createElement("h2", {
    style: {
      color: "#fff",
      fontSize: "var(--text-h3)",
      fontWeight: "var(--fw-semibold)",
      margin: "12px 0 8px",
      letterSpacing: "var(--ls-tight)"
    }
  }, "Good morning, Priya. Spend is pacing 6% hot \u2014 but ROAS is up."), /*#__PURE__*/React.createElement("p", {
    style: {
      color: "var(--periwinkle-200)",
      fontSize: "var(--text-base)",
      lineHeight: "var(--lh-normal)",
      maxWidth: 720
    }
  }, "Paid social drove 38% of pipeline this week. I've flagged two budget reallocations worth an estimated", /*#__PURE__*/React.createElement("strong", {
    style: {
      color: "#fff"
    }
  }, " +$48K in revenue"), ". Three creatives are entering fatigue."), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      gap: 12,
      marginTop: 18
    }
  }, /*#__PURE__*/React.createElement(Button, {
    variant: "primary",
    size: "sm"
  }, "Review reallocations"), /*#__PURE__*/React.createElement(Button, {
    variant: "ghost",
    size: "sm",
    style: {
      color: "#fff"
    }
  }, "See full briefing")))));
}
function AskAlfred() {
  const [q, setQ] = React.useState("");
  const chips = ["Why did CAC rise last week?", "Forecast Q3 pipeline", "Which channel is underspending?"];
  return /*#__PURE__*/React.createElement(Card, {
    padding: 20,
    shadow: "sm",
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 14
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 10
    }
  }, /*#__PURE__*/React.createElement("img", {
    src: "../../assets/logos/alfred-icon.svg",
    alt: "",
    style: {
      height: 26
    }
  }), /*#__PURE__*/React.createElement("span", {
    style: {
      fontWeight: "var(--fw-bold)",
      fontSize: "var(--text-base)"
    }
  }, "Ask Alfred"), /*#__PURE__*/React.createElement(Badge, {
    tone: "info"
  }, "on-demand")), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 10,
      padding: "6px 6px 6px 18px",
      background: "var(--gray-50)",
      border: "1px solid var(--border-subtle)",
      borderRadius: "var(--radius-pill)"
    }
  }, /*#__PURE__*/React.createElement("input", {
    value: q,
    onChange: e => setQ(e.target.value),
    placeholder: "Ask anything about your marketing performance\u2026",
    style: {
      flex: 1,
      border: "none",
      background: "transparent",
      fontFamily: "var(--font-sans)",
      fontSize: "var(--text-base)",
      color: "var(--text-primary)"
    }
  }), /*#__PURE__*/React.createElement(Button, {
    variant: "subtle",
    size: "sm",
    iconRight: /*#__PURE__*/React.createElement(window.NavGlyph, {
      d: window.AppGlyphs.send,
      size: 15
    })
  }, "Ask")), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      gap: 8,
      flexWrap: "wrap"
    }
  }, chips.map(c => /*#__PURE__*/React.createElement("button", {
    key: c,
    onClick: () => setQ(c),
    style: {
      border: "1px solid var(--border-default)",
      background: "var(--surface-card)",
      cursor: "pointer",
      padding: "7px 14px",
      borderRadius: "var(--radius-pill)",
      color: "var(--text-secondary)",
      fontFamily: "var(--font-sans)",
      fontSize: "var(--text-sm)",
      fontWeight: "var(--fw-medium)"
    }
  }, c))));
}
function Dashboard() {
  return /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 22,
      maxWidth: 1180,
      margin: "0 auto"
    }
  }, /*#__PURE__*/React.createElement(Briefing, null), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "repeat(4, 1fr)",
      gap: 16
    }
  }, /*#__PURE__*/React.createElement(KpiCard, {
    label: "Blended ROAS",
    value: "4.8x",
    delta: "+12.4%",
    direction: "up",
    caption: "vs last 30d",
    icon: "trend-up",
    iconRoot: IR
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Marketing spend",
    value: "$312K",
    delta: "+6.1%",
    direction: "up",
    valence: "bad",
    caption: "pacing hot",
    icon: "budget",
    iconRoot: IR
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Blended CAC",
    value: "$184",
    delta: "-8.0%",
    direction: "down",
    valence: "good",
    caption: "improving",
    icon: "channel-mix",
    iconRoot: IR
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "MQL \u2192 SQL",
    value: "34%",
    delta: "0.0%",
    direction: "flat",
    caption: "flat WoW",
    icon: "mql",
    iconRoot: IR
  })), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "1.55fr 1fr",
      gap: 22,
      alignItems: "start"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 14
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 10
    }
  }, /*#__PURE__*/React.createElement("h3", {
    style: {
      fontSize: "var(--text-h4)",
      fontWeight: "var(--fw-bold)"
    }
  }, "Real-time decision alerts"), /*#__PURE__*/React.createElement(Badge, {
    tone: "danger",
    dot: true
  }, "3 need action"), /*#__PURE__*/React.createElement("a", {
    href: "#",
    onClick: e => e.preventDefault(),
    style: {
      marginLeft: "auto",
      fontSize: "var(--text-sm)",
      fontWeight: "var(--fw-bold)"
    }
  }, "View all")), /*#__PURE__*/React.createElement(DecisionAlert, {
    priority: "high",
    time: "12m ago",
    iconRoot: IR,
    title: "Google Ads over budget",
    insight: "Brand campaign will exhaust its monthly cap in 4 days at current pacing. Shift $18K to Performance Max to protect non-brand coverage.",
    action: "Reallocate budget"
  }), /*#__PURE__*/React.createElement(DecisionAlert, {
    priority: "opportunity",
    time: "1h ago",
    iconRoot: IR,
    title: "LinkedIn CPL down 22%",
    insight: "Cost-per-lead dropped sharply on the new ABM audience. I recommend scaling spend +30% while efficiency holds.",
    action: "Scale campaign"
  }), /*#__PURE__*/React.createElement(DecisionAlert, {
    priority: "medium",
    time: "3h ago",
    iconRoot: IR,
    title: "Creative fatigue detected",
    insight: "Three Meta creatives crossed the frequency-3.0 threshold; CTR is down 14% over 7 days. Queue refreshes from the creative library."
  })), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 22
    }
  }, /*#__PURE__*/React.createElement(Card, {
    padding: 22,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 14
    }
  }, /*#__PURE__*/React.createElement("h3", {
    style: {
      fontSize: "var(--text-h4)",
      fontWeight: "var(--fw-bold)"
    }
  }, "Channel mix"), /*#__PURE__*/React.createElement(IconButton, {
    name: "refresh",
    iconRoot: IR,
    variant: "ghost",
    title: "Refresh"
  })), [["Paid social", 38, "var(--orange-500)"], ["Search", 26, "var(--periwinkle-400)"], ["Email", 18, "var(--orange-300)"], ["Organic", 12, "var(--periwinkle-600)"], ["Other", 6, "var(--gray-200)"]].map(([n, p, c]) => /*#__PURE__*/React.createElement("div", {
    key: n,
    style: {
      display: "flex",
      alignItems: "center",
      gap: 12,
      marginBottom: 12
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      width: 78,
      fontSize: "var(--text-sm)",
      color: "var(--text-secondary)"
    }
  }, n), /*#__PURE__*/React.createElement("div", {
    style: {
      flex: 1,
      height: 8,
      background: "var(--gray-100)",
      borderRadius: "var(--radius-pill)",
      overflow: "hidden"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      width: `${p}%`,
      height: "100%",
      background: c,
      borderRadius: "var(--radius-pill)"
    }
  })), /*#__PURE__*/React.createElement("span", {
    style: {
      width: 34,
      textAlign: "right",
      fontSize: "var(--text-sm)",
      fontWeight: "var(--fw-bold)",
      color: "var(--text-primary)",
      fontVariantNumeric: "tabular-nums"
    }
  }, p, "%")))), /*#__PURE__*/React.createElement(AskAlfred, null))));
}
window.Dashboard = Dashboard;

/* function declarations, global as they were under the browser compiler */
window.Briefing = Briefing;
window.AskAlfred = AskAlfred;
window.Dashboard = Dashboard;
})();
