/* GENERATED by scripts/build-kits.mjs from ui_kits/app/Screens.jsx — do not edit. */
(function () {
/* ============================================================
   Alfred workspace — secondary screens for the expansive app kit.
   KPI Cockpit · Spend & ROI · Decision Alerts · Integrations · Settings.
   Light theme. Composed from the design-system primitives, matching
   the Dashboard's language (soft cards, gradient accents, first-person voice).
   ============================================================ */
const {
  Card,
  KpiCard,
  ProgressBar,
  Badge,
  Button,
  IconButton,
  Icon,
  Avatar,
  Tabs,
  Switch,
  Checkbox,
  Input,
  Modal
} = window.AlfredAIDesignSystem_1ce241;
const ICN = "../../assets/icons";

/* ——— shared bits ——— */
const SectionHead = ({
  title,
  right,
  sub
}) => /*#__PURE__*/React.createElement("div", {
  style: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 14
  }
}, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("h3", {
  style: {
    fontSize: "var(--text-h4)",
    fontWeight: "var(--fw-bold)",
    letterSpacing: "var(--ls-tight)"
  }
}, title), sub && /*#__PURE__*/React.createElement("div", {
  style: {
    fontSize: "var(--text-sm)",
    color: "var(--text-muted)",
    marginTop: 2
  }
}, sub)), right && /*#__PURE__*/React.createElement("div", {
  style: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 10
  }
}, right));

/* A tiny on-brand area sparkline (periwinkle→orange fill). */
function Sparkline({
  points,
  w = 640,
  h = 180,
  id = "spark"
}) {
  const max = Math.max(...points),
    min = Math.min(...points);
  const nx = i => i / (points.length - 1) * w;
  const ny = v => h - (v - min) / (max - min || 1) * (h - 24) - 12;
  const line = points.map((v, i) => `${i === 0 ? "M" : "L"} ${nx(i).toFixed(1)} ${ny(v).toFixed(1)}`).join(" ");
  const area = `${line} L ${w} ${h} L 0 ${h} Z`;
  return /*#__PURE__*/React.createElement("svg", {
    viewBox: `0 0 ${w} ${h}`,
    width: "100%",
    height: h,
    preserveAspectRatio: "none",
    style: {
      display: "block"
    }
  }, /*#__PURE__*/React.createElement("defs", null, /*#__PURE__*/React.createElement("linearGradient", {
    id: `${id}-l`,
    x1: "0",
    y1: "0",
    x2: "1",
    y2: "0"
  }, /*#__PURE__*/React.createElement("stop", {
    offset: "0%",
    stopColor: "#A7A7FC"
  }), /*#__PURE__*/React.createElement("stop", {
    offset: "100%",
    stopColor: "#FF8431"
  })), /*#__PURE__*/React.createElement("linearGradient", {
    id: `${id}-f`,
    x1: "0",
    y1: "0",
    x2: "0",
    y2: "1"
  }, /*#__PURE__*/React.createElement("stop", {
    offset: "0%",
    stopColor: "rgba(255,132,49,0.20)"
  }), /*#__PURE__*/React.createElement("stop", {
    offset: "100%",
    stopColor: "rgba(255,132,49,0)"
  }))), /*#__PURE__*/React.createElement("path", {
    d: area,
    fill: `url(#${id}-f)`
  }), /*#__PURE__*/React.createElement("path", {
    d: line,
    fill: "none",
    stroke: `url(#${id}-l)`,
    strokeWidth: "3",
    strokeLinecap: "round",
    strokeLinejoin: "round"
  }));
}

/* ======================= KPI COCKPIT ======================= */
function KpiCockpit() {
  const [metric, setMetric] = React.useState("roas");
  const series = {
    roas: [3.1, 3.4, 3.2, 3.8, 4.0, 3.7, 4.2, 4.5, 4.3, 4.8],
    cac: [240, 232, 236, 220, 210, 214, 200, 192, 196, 184],
    pipe: [120, 140, 132, 168, 180, 176, 205, 230, 224, 268]
  };
  const funnel = [["Visitors", 100, "var(--periwinkle-400)"], ["MQL", 64, "var(--periwinkle-500)"], ["SQL", 34, "var(--orange-300)"], ["Opportunity", 19, "var(--orange-400)"], ["Won", 8, "var(--orange-500)"]];
  return /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 22,
      maxWidth: 1180,
      margin: "0 auto"
    }
  }, /*#__PURE__*/React.createElement(Card, {
    padding: 14,
    tone: "surface",
    shadow: "sm",
    style: {
      display: "flex",
      alignItems: "center",
      gap: 10
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      width: 16,
      height: 16,
      borderRadius: "var(--radius-pill)",
      background: "var(--gradient-brand)",
      flex: "none"
    }
  }), /*#__PURE__*/React.createElement("span", {
    style: {
      fontSize: 13.5,
      color: "var(--text-secondary)"
    }
  }, "Everything is on plan except one thing \u2014 Meta fatigue is inflating blended CAC. The fix is drafted in Decision alerts.")), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "repeat(4, 1fr)",
      gap: 16
    }
  }, /*#__PURE__*/React.createElement(KpiCard, {
    label: "Blended ROAS",
    value: "4.8x",
    delta: "+12.4%",
    direction: "up",
    caption: "vs last 30d",
    icon: "trend-up",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Marketing Spend",
    value: "$312K",
    delta: "+6.1%",
    direction: "up",
    valence: "bad",
    caption: "pacing hot",
    icon: "budget",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Blended CAC",
    value: "$184",
    delta: "-8.0%",
    direction: "down",
    valence: "good",
    caption: "improving",
    icon: "channel-mix",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "MQL \u2192 SQL",
    value: "34%",
    delta: "0.0%",
    direction: "flat",
    caption: "flat WoW",
    icon: "mql",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Pipeline created",
    value: "$2.68M",
    delta: "+19.5%",
    direction: "up",
    caption: "this quarter",
    icon: "trend-up",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "LTV : CAC",
    value: "4.1:1",
    delta: "+0.3",
    direction: "up",
    caption: "healthy",
    icon: "trend-up",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Avg. CPL",
    value: "$58",
    delta: "-14.0%",
    direction: "down",
    valence: "good",
    caption: "LinkedIn ABM",
    icon: "trend-down",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Win rate",
    value: "22%",
    delta: "+1.8%",
    direction: "up",
    caption: "vs last Q",
    icon: "trend-up",
    iconRoot: ICN
  })), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "1.55fr 1fr",
      gap: 22,
      alignItems: "start"
    }
  }, /*#__PURE__*/React.createElement(Card, {
    padding: 24,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement(SectionHead, {
    title: "Performance trend",
    sub: "Last 10 weeks",
    right: /*#__PURE__*/React.createElement(Tabs, {
      value: metric,
      onChange: setMetric,
      tabs: [{
        id: "roas",
        label: "ROAS"
      }, {
        id: "cac",
        label: "CAC"
      }, {
        id: "pipe",
        label: "Pipeline"
      }]
    })
  }), /*#__PURE__*/React.createElement(Sparkline, {
    points: series[metric],
    id: metric
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      justifyContent: "space-between",
      marginTop: 6,
      fontSize: "var(--text-xs)",
      color: "var(--text-muted)"
    }
  }, ["W1", "W2", "W3", "W4", "W5", "W6", "W7", "W8", "W9", "W10"].map(w => /*#__PURE__*/React.createElement("span", {
    key: w
  }, w)))), /*#__PURE__*/React.createElement(Card, {
    padding: 24,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement(SectionHead, {
    title: "Funnel conversion",
    sub: "This quarter"
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 12
    }
  }, funnel.map(([n, p, c]) => /*#__PURE__*/React.createElement("div", {
    key: n
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      justifyContent: "space-between",
      marginBottom: 6,
      fontSize: "var(--text-sm)"
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      color: "var(--text-secondary)"
    }
  }, n), /*#__PURE__*/React.createElement("span", {
    style: {
      fontWeight: "var(--fw-bold)",
      color: "var(--text-primary)",
      fontVariantNumeric: "tabular-nums"
    }
  }, p, "%")), /*#__PURE__*/React.createElement("div", {
    style: {
      height: 10,
      background: "var(--gray-100)",
      borderRadius: "var(--radius-pill)",
      overflow: "hidden"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      width: `${p}%`,
      height: "100%",
      background: c,
      borderRadius: "var(--radius-pill)"
    }
  }))))))));
}

/* ======================= SPEND & ROI ======================= */
function SpendRoi() {
  const channels = [["Paid social", 38, "var(--orange-500)"], ["Search", 26, "var(--periwinkle-400)"], ["Email", 18, "var(--orange-300)"], ["Organic", 12, "var(--periwinkle-600)"], ["Events", 6, "var(--slate-300)"]];
  const rows = [["Performance Max — Q2", "$84.2K", "5.1x", "$142", "high"], ["Meta — Retargeting", "$61.0K", "4.6x", "$168", "high"], ["LinkedIn — ABM tier 1", "$48.5K", "3.9x", "$210", "med"], ["Brand search", "$39.1K", "6.8x", "$96", "high"], ["YouTube — Awareness", "$27.4K", "2.1x", "$320", "low"]];
  const statusTone = {
    high: "success",
    med: "warning",
    low: "danger"
  };
  const statusText = {
    high: "Scaling",
    med: "Holding",
    low: "At risk"
  };
  return /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 22,
      maxWidth: 1180,
      margin: "0 auto"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "repeat(3, 1fr)",
      gap: 16
    }
  }, /*#__PURE__*/React.createElement(KpiCard, {
    label: "Spend this month",
    value: "$312K",
    delta: "+6.1%",
    direction: "up",
    valence: "bad",
    caption: "of $295K plan",
    icon: "budget",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Blended ROAS",
    value: "4.8x",
    delta: "+12.4%",
    direction: "up",
    caption: "above 4.0x target",
    icon: "trend-up",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Wasted spend",
    value: "$11.4K",
    delta: "-31%",
    direction: "down",
    valence: "good",
    caption: "I reclaimed it",
    icon: "trend-down",
    iconRoot: ICN
  })), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: 22,
      alignItems: "start"
    }
  }, /*#__PURE__*/React.createElement(Card, {
    padding: 24,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement(SectionHead, {
    title: "Budget pacing",
    sub: "17 days into the cycle",
    right: /*#__PURE__*/React.createElement(Badge, {
      tone: "warning",
      dot: true
    }, "6% hot")
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 18
    }
  }, [["Total budget", 62, "gradient"], ["Search", 71, "plain"], ["Paid social", 58, "plain"]].map(([n, v, tone]) => /*#__PURE__*/React.createElement("div", {
    key: n
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      justifyContent: "space-between",
      marginBottom: 7,
      fontSize: "var(--text-sm)"
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      color: "var(--text-secondary)"
    }
  }, n), /*#__PURE__*/React.createElement("span", {
    style: {
      fontWeight: "var(--fw-bold)",
      fontVariantNumeric: "tabular-nums"
    }
  }, v, "%")), /*#__PURE__*/React.createElement(ProgressBar, {
    value: v,
    tone: tone,
    height: 9
  }))))), /*#__PURE__*/React.createElement(Card, {
    padding: 24,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement(SectionHead, {
    title: "Channel mix",
    sub: "Share of spend",
    right: /*#__PURE__*/React.createElement(IconButton, {
      name: "export",
      iconRoot: ICN,
      variant: "ghost",
      title: "Export"
    })
  }), channels.map(([n, p, c]) => /*#__PURE__*/React.createElement("div", {
    key: n,
    style: {
      display: "flex",
      alignItems: "center",
      gap: 12,
      marginBottom: 13
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      width: 84,
      fontSize: "var(--text-sm)",
      color: "var(--text-secondary)"
    }
  }, n), /*#__PURE__*/React.createElement("div", {
    style: {
      flex: 1,
      height: 8,
      background: "var(--gray-100)",
      borderRadius: "var(--radius-pill)",
      overflow: "hidden"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      width: `${p}%`,
      height: "100%",
      background: c,
      borderRadius: "var(--radius-pill)"
    }
  })), /*#__PURE__*/React.createElement("span", {
    style: {
      width: 34,
      textAlign: "right",
      fontSize: "var(--text-sm)",
      fontWeight: "var(--fw-bold)",
      fontVariantNumeric: "tabular-nums"
    }
  }, p, "%"))))), /*#__PURE__*/React.createElement(Card, {
    padding: 0,
    shadow: "sm",
    style: {
      overflow: "hidden"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      padding: "20px 24px 0"
    }
  }, /*#__PURE__*/React.createElement(SectionHead, {
    title: "Campaigns",
    sub: "Ranked by spend",
    right: /*#__PURE__*/React.createElement(Button, {
      variant: "subtle",
      size: "sm",
      iconLeft: /*#__PURE__*/React.createElement(Icon, {
        name: "sort",
        root: ICN,
        size: 15
      })
    }, "Sort")
  })), /*#__PURE__*/React.createElement("table", {
    style: {
      width: "100%",
      borderCollapse: "collapse",
      fontFamily: "var(--font-sans)"
    }
  }, /*#__PURE__*/React.createElement("thead", null, /*#__PURE__*/React.createElement("tr", {
    style: {
      textAlign: "left",
      color: "var(--text-muted)",
      fontSize: "var(--text-xs)",
      textTransform: "uppercase",
      letterSpacing: "var(--ls-caps)"
    }
  }, ["Campaign", "Spend", "ROAS", "CAC", "Status"].map((h, i) => /*#__PURE__*/React.createElement("th", {
    key: h,
    style: {
      padding: "12px 24px",
      fontWeight: "var(--fw-bold)",
      textAlign: i > 0 && i < 4 ? "right" : "left"
    }
  }, h)))), /*#__PURE__*/React.createElement("tbody", null, rows.map(([name, spend, roas, cac, st], i) => /*#__PURE__*/React.createElement("tr", {
    key: name,
    style: {
      borderTop: "1px solid var(--border-subtle)",
      fontSize: "var(--text-sm)"
    }
  }, /*#__PURE__*/React.createElement("td", {
    style: {
      padding: "15px 24px",
      fontWeight: "var(--fw-bold)",
      color: "var(--text-primary)"
    }
  }, name), /*#__PURE__*/React.createElement("td", {
    style: {
      padding: "15px 24px",
      textAlign: "right",
      fontVariantNumeric: "tabular-nums",
      color: "var(--text-body)"
    }
  }, spend), /*#__PURE__*/React.createElement("td", {
    style: {
      padding: "15px 24px",
      textAlign: "right",
      fontVariantNumeric: "tabular-nums",
      fontWeight: "var(--fw-bold)",
      color: "var(--text-primary)"
    }
  }, roas), /*#__PURE__*/React.createElement("td", {
    style: {
      padding: "15px 24px",
      textAlign: "right",
      fontVariantNumeric: "tabular-nums",
      color: "var(--text-body)"
    }
  }, cac), /*#__PURE__*/React.createElement("td", {
    style: {
      padding: "15px 24px"
    }
  }, /*#__PURE__*/React.createElement(Badge, {
    tone: statusTone[st],
    dot: true
  }, statusText[st]))))))));
}

/* ======================= DECISION ALERTS ======================= */
/* Local alert card: same visual language as the DS DecisionAlert, but the CTA
   area is controllable — a subtle "review" CTA at rest, an executing state
   (brand badge + undo) once a draft is approved. */
const ALERT_META = {
  high: {
    rail: "var(--danger-500)",
    icon: "alert-warning",
    badge: "danger",
    label: "High"
  },
  medium: {
    rail: "var(--orange-500)",
    icon: "alert-warning",
    badge: "warning",
    label: "Medium"
  },
  low: {
    rail: "var(--periwinkle-400)",
    icon: "bookmark",
    badge: "info",
    label: "Low"
  },
  opportunity: {
    rail: "var(--success-500)",
    icon: "trend-up",
    badge: "success",
    label: "Opportunity"
  }
};
function AlertCard({
  alert,
  executing,
  onReview,
  onUndo
}) {
  const p = ALERT_META[alert.priority] || ALERT_META.medium;
  return /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      gap: 14,
      alignItems: "flex-start",
      background: "var(--surface-card)",
      border: "1px solid var(--border-subtle)",
      borderRadius: "var(--radius-xl)",
      padding: "16px 18px 16px 14px",
      boxShadow: "var(--shadow-xs)",
      position: "relative",
      overflow: "hidden"
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      position: "absolute",
      left: 0,
      top: 0,
      bottom: 0,
      width: 4,
      background: p.rail
    }
  }), /*#__PURE__*/React.createElement("span", {
    style: {
      width: 38,
      height: 38,
      borderRadius: "var(--radius-md)",
      flex: "none",
      marginLeft: 6,
      background: "var(--orange-50)",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center"
    }
  }, /*#__PURE__*/React.createElement(Icon, {
    name: p.icon,
    size: 18,
    color: p.rail,
    root: ICN
  })), /*#__PURE__*/React.createElement("div", {
    style: {
      flex: 1,
      minWidth: 0
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 10,
      marginBottom: 4
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      fontFamily: "var(--font-sans)",
      fontSize: "var(--text-base)",
      fontWeight: "var(--fw-bold)",
      color: "var(--text-primary)"
    }
  }, alert.title), /*#__PURE__*/React.createElement(Badge, {
    tone: p.badge,
    dot: true
  }, p.label), alert.time && /*#__PURE__*/React.createElement("span", {
    style: {
      marginLeft: "auto",
      fontFamily: "var(--font-sans)",
      fontSize: "var(--text-xs)",
      color: "var(--text-muted)"
    }
  }, alert.time)), /*#__PURE__*/React.createElement("p", {
    style: {
      fontFamily: "var(--font-sans)",
      fontSize: "var(--text-sm)",
      color: "var(--text-secondary)",
      lineHeight: "var(--lh-normal)",
      margin: 0
    }
  }, alert.insight), executing ? /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 10,
      marginTop: 12,
      flexWrap: "wrap"
    }
  }, /*#__PURE__*/React.createElement(Badge, {
    tone: "brand",
    dot: true
  }, "Executing"), /*#__PURE__*/React.createElement(Button, {
    variant: "ghost",
    size: "sm",
    onClick: onUndo
  }, "Undo"), /*#__PURE__*/React.createElement("span", {
    style: {
      fontFamily: "var(--font-sans)",
      fontSize: 12.5,
      color: "var(--text-muted)"
    }
  }, "I'll confirm in Slack when it's live.")) : alert.action ? /*#__PURE__*/React.createElement(Button, {
    variant: "subtle",
    size: "sm",
    style: {
      marginTop: 12
    },
    onClick: onReview
  }, alert.action) : null));
}
function AlertsInbox() {
  const [filter, setFilter] = React.useState("all");
  const [reviewId, setReviewId] = React.useState(null);
  const [executing, setExecuting] = React.useState({});
  const all = [{
    id: "google-budget",
    priority: "high",
    time: "12m ago",
    title: "Google Ads over budget",
    insight: "Brand campaign will exhaust its monthly cap in 4 days at current pacing. Shift $18K to Performance Max to protect non-brand coverage.",
    action: "Reallocate budget",
    tag: "high",
    draft: {
      what: "Search daily budget",
      from: "$30K",
      to: "$12K cap",
      impact: "Protects non-brand coverage · est. +$48K pipeline",
      approve: "Approve — move $18K"
    }
  }, {
    id: "linkedin-scale",
    priority: "opportunity",
    time: "1h ago",
    title: "LinkedIn CPL down 22%",
    insight: "Cost-per-lead dropped sharply on the new ABM audience. I recommend scaling spend +30% while efficiency holds.",
    action: "Scale campaign",
    tag: "opportunity",
    draft: {
      what: "LinkedIn ABM daily budget",
      from: "$1.6K",
      to: "$2.1K (+30%)",
      impact: "Holds $58 CPL at scale · est. +$12K pipeline per month",
      approve: "Approve — scale +30%"
    }
  }, {
    id: "creative-fatigue",
    priority: "medium",
    time: "3h ago",
    title: "Creative fatigue detected",
    insight: "Three Meta creatives crossed the frequency-3.0 threshold; CTR is down 14% over 7 days. Queue refreshes from the creative library.",
    action: "Queue refreshes",
    tag: "high",
    draft: {
      what: "Meta retargeting creative",
      from: "3 fatigued ads",
      to: "3 fresh variants",
      impact: "Recovers ~14% CTR · protects $61K retargeting spend",
      approve: "Approve — queue refreshes"
    }
  }, {
    id: "search-cap",
    priority: "opportunity",
    time: "5h ago",
    title: "Search impression share rising",
    insight: "Non-brand impression share climbed to 71%. There is room to capture an estimated +$22K pipeline by lifting the Search cap 15%.",
    action: "Raise cap",
    tag: "opportunity",
    draft: {
      what: "Search monthly cap",
      from: "$39.1K",
      to: "$45.0K (+15%)",
      impact: "Captures rising demand · est. +$22K pipeline",
      approve: "Approve — raise cap 15%"
    }
  }, {
    id: "email-steady",
    priority: "low",
    time: "Yesterday",
    title: "Email engagement steady",
    insight: "Open rate held at 41% after the subject-line test. No action needed — I'll keep watching the next send.",
    tag: "resolved"
  }];
  const shown = filter === "all" ? all : all.filter(a => a.tag === filter);
  const review = all.find(a => a.id === reviewId) || null;
  const openFirstDraft = () => {
    const next = all.find(a => a.draft && !executing[a.id]) || all.find(a => a.draft);
    if (next) setReviewId(next.id);
  };
  const approve = () => {
    setExecuting(prev => ({
      ...prev,
      [reviewId]: true
    }));
    setReviewId(null);
  };
  return /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "1.6fr 1fr",
      gap: 22,
      alignItems: "start",
      maxWidth: 1180,
      margin: "0 auto"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 14
    }
  }, /*#__PURE__*/React.createElement(Tabs, {
    value: filter,
    onChange: setFilter,
    tabs: [{
      id: "all",
      label: "All"
    }, {
      id: "high",
      label: "Needs action"
    }, {
      id: "opportunity",
      label: "Opportunities"
    }, {
      id: "resolved",
      label: "Resolved"
    }]
  }), shown.map(a => /*#__PURE__*/React.createElement(AlertCard, {
    key: a.id,
    alert: a,
    executing: !!executing[a.id],
    onReview: () => setReviewId(a.id),
    onUndo: () => setExecuting(prev => {
      const next = {
        ...prev
      };
      delete next[a.id];
      return next;
    })
  }))), /*#__PURE__*/React.createElement(Card, {
    tone: "ink",
    padding: 24,
    radius: "var(--radius-2xl)",
    style: {
      position: "relative",
      overflow: "hidden"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      position: "absolute",
      inset: 0,
      background: "var(--glow-orange)",
      opacity: 0.5
    }
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      position: "relative"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 10,
      marginBottom: 14
    }
  }, /*#__PURE__*/React.createElement("img", {
    src: "../../assets/logos/alfred-icon-white.svg",
    alt: "",
    style: {
      height: 24
    }
  }), /*#__PURE__*/React.createElement("span", {
    style: {
      color: "#fff",
      fontWeight: "var(--fw-bold)",
      fontSize: "var(--text-base)"
    }
  }, "Alfred's read on today")), /*#__PURE__*/React.createElement("p", {
    style: {
      color: "rgba(255,255,255,0.78)",
      fontSize: "var(--text-base)",
      lineHeight: "var(--lh-relaxed)",
      margin: "0 0 18px"
    }
  }, "Two items need a decision and both are upside. Reallocating Google Ads spend protects non-brand coverage; scaling LinkedIn while CPL is low is worth an estimated ", /*#__PURE__*/React.createElement("strong", {
    style: {
      color: "#fff"
    }
  }, "+$48K in pipeline"), ". I've drafted both \u2014 approve and I'll execute."), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 10
    }
  }, [["Needs action", "2"], ["Opportunities", "2"], ["Resolved this week", "9"]].map(([l, n]) => /*#__PURE__*/React.createElement("div", {
    key: l,
    style: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "10px 0",
      borderTop: "1px solid rgba(255,255,255,0.10)"
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      color: "rgba(255,255,255,0.74)",
      fontSize: "var(--text-sm)"
    }
  }, l), /*#__PURE__*/React.createElement("span", {
    style: {
      color: "#fff",
      fontWeight: "var(--fw-bold)",
      fontVariantNumeric: "tabular-nums"
    }
  }, n)))), /*#__PURE__*/React.createElement(Button, {
    variant: "subtle",
    size: "sm",
    fullWidth: true,
    style: {
      marginTop: 18
    },
    onClick: openFirstDraft
  }, "Review drafts"))), review && /*#__PURE__*/React.createElement(Modal, {
    open: true,
    onClose: () => setReviewId(null),
    title: `Review draft — ${review.title}`,
    footer: /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement(Button, {
      variant: "ghost",
      onClick: () => setReviewId(null)
    }, "Cancel"), /*#__PURE__*/React.createElement(Button, {
      variant: "primary",
      onClick: approve
    }, review.draft.approve))
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 14
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      padding: "12px 14px",
      background: "var(--surface-sunken)",
      borderRadius: "var(--radius-md)",
      fontSize: "var(--text-sm)"
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      color: "var(--text-secondary)"
    }
  }, review.draft.what), /*#__PURE__*/React.createElement("span", {
    style: {
      display: "inline-flex",
      alignItems: "center",
      gap: 8,
      fontVariantNumeric: "tabular-nums"
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      color: "var(--text-muted)",
      textDecoration: "line-through"
    }
  }, review.draft.from), /*#__PURE__*/React.createElement("span", {
    style: {
      color: "var(--text-muted)"
    }
  }, "\u2192"), /*#__PURE__*/React.createElement("span", {
    style: {
      fontWeight: "var(--fw-bold)",
      color: "var(--text-primary)"
    }
  }, review.draft.to))), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      fontSize: "var(--text-sm)",
      color: "var(--text-secondary)"
    }
  }, /*#__PURE__*/React.createElement(Icon, {
    name: "trend-up",
    root: ICN,
    size: 15,
    color: "var(--success-500)"
  }), /*#__PURE__*/React.createElement("span", null, review.draft.impact)), /*#__PURE__*/React.createElement("p", {
    style: {
      margin: 0,
      paddingTop: 12,
      borderTop: "1px solid var(--border-subtle)",
      fontSize: "var(--text-sm)",
      color: "var(--text-muted)",
      lineHeight: "var(--lh-normal)"
    }
  }, "I'll watch this for 48 hours and can revert it the moment it underperforms."))));
}

/* ======================= INTEGRATIONS ======================= */
function Integrations() {
  const connected = [["Google Ads", "Campaigns · spend · ROAS", "var(--orange-500)"], ["Meta Ads", "Paid social · creative", "var(--periwinkle-500)"], ["HubSpot", "CRM · pipeline · MQLs", "var(--orange-400)"], ["LinkedIn Ads", "ABM · lead gen", "var(--periwinkle-400)"], ["GA4", "Web analytics · attribution", "var(--orange-300)"], ["Salesforce", "Opportunities · revenue", "var(--periwinkle-600)"]];
  const available = [["Looker", "BI dashboards"], ["Slack", "Alerts & briefings"], ["Snowflake", "Warehouse sync"], ["Stripe", "Revenue & billing"]];
  const Tile = ({
    children,
    style
  }) => /*#__PURE__*/React.createElement(Card, {
    padding: 20,
    shadow: "sm",
    interactive: true,
    style: {
      display: "flex",
      alignItems: "center",
      gap: 14,
      ...style
    }
  }, children);
  const Glyph = ({
    color
  }) => /*#__PURE__*/React.createElement("div", {
    style: {
      width: 42,
      height: 42,
      borderRadius: "var(--radius-md)",
      flex: "none",
      background: color,
      display: "flex",
      alignItems: "center",
      justifyContent: "center"
    }
  }, /*#__PURE__*/React.createElement(Icon, {
    name: "web-stack-connected",
    root: ICN,
    size: 22,
    color: "var(--text-on-orange)"
  }));
  return /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 26,
      maxWidth: 1180,
      margin: "0 auto"
    }
  }, /*#__PURE__*/React.createElement(Card, {
    tone: "gradient",
    padding: 24,
    style: {
      display: "flex",
      alignItems: "center",
      gap: 18
    }
  }, /*#__PURE__*/React.createElement(Icon, {
    name: "integration-success",
    root: ICN,
    size: 30,
    color: "#fff"
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      flex: 1
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      color: "#fff",
      fontWeight: "var(--fw-bold)",
      fontSize: "var(--text-h4)"
    }
  }, "6 sources connected"), /*#__PURE__*/React.createElement("div", {
    style: {
      color: "rgba(255,255,255,0.92)",
      fontSize: "var(--text-sm)"
    }
  }, "I'm reading from your full marketing stack. The more you connect, the sharper my memory.")), /*#__PURE__*/React.createElement(Button, {
    variant: "secondary",
    size: "sm",
    style: {
      background: "#fff",
      color: "var(--ink-900)"
    }
  }, "Add a source")), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement(SectionHead, {
    title: "Connected",
    sub: "Syncing now"
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "repeat(3, 1fr)",
      gap: 16
    }
  }, connected.map(([name, desc, c]) => /*#__PURE__*/React.createElement(Tile, {
    key: name
  }, /*#__PURE__*/React.createElement(Glyph, {
    color: c
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      flex: 1,
      minWidth: 0
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      fontWeight: "var(--fw-bold)",
      color: "var(--text-primary)",
      fontSize: "var(--text-base)"
    }
  }, name), /*#__PURE__*/React.createElement("div", {
    style: {
      fontSize: "var(--text-xs)",
      color: "var(--text-muted)"
    }
  }, desc)), /*#__PURE__*/React.createElement(Badge, {
    tone: "success",
    dot: true
  }, "Live"))))), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement(SectionHead, {
    title: "Available",
    sub: "One click to connect"
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "repeat(4, 1fr)",
      gap: 16
    }
  }, available.map(([name, desc]) => /*#__PURE__*/React.createElement(Tile, {
    key: name
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      width: 42,
      height: 42,
      borderRadius: "var(--radius-md)",
      flex: "none",
      background: "var(--gray-100)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center"
    }
  }, /*#__PURE__*/React.createElement(Icon, {
    name: "web-clarity",
    root: ICN,
    size: 22,
    color: "var(--text-muted)"
  })), /*#__PURE__*/React.createElement("div", {
    style: {
      flex: 1,
      minWidth: 0
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      fontWeight: "var(--fw-bold)",
      color: "var(--text-primary)",
      fontSize: "var(--text-base)"
    }
  }, name), /*#__PURE__*/React.createElement("div", {
    style: {
      fontSize: "var(--text-xs)",
      color: "var(--text-muted)"
    }
  }, desc)), /*#__PURE__*/React.createElement(Button, {
    variant: "subtle",
    size: "sm"
  }, "Connect"))))));
}

/* ======================= SETTINGS ======================= */
function Settings() {
  const [pane, setPane] = React.useState("profile");
  const [name, setName] = React.useState("Priya Menon");
  const [email, setEmail] = React.useState("priya@northwindlabs.com");
  const [brief, setBrief] = React.useState(true);
  const [alerts, setAlerts] = React.useState(true);
  const [digest, setDigest] = React.useState(false);
  const panes = [["profile", "Profile"], ["workspace", "Workspace"], ["notifications", "Notifications"], ["security", "Security"]];
  const NavRow = ([id, label]) => /*#__PURE__*/React.createElement("button", {
    key: id,
    onClick: () => setPane(id),
    style: {
      textAlign: "left",
      border: "none",
      cursor: "pointer",
      padding: "10px 14px",
      borderRadius: "var(--radius-md)",
      background: pane === id ? "var(--orange-50)" : "transparent",
      color: pane === id ? "var(--orange-600)" : "var(--text-secondary)",
      fontFamily: "var(--font-sans)",
      fontSize: "var(--text-sm)",
      fontWeight: pane === id ? "var(--fw-bold)" : "var(--fw-medium)"
    }
  }, label);
  return /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "200px 1fr",
      gap: 28,
      maxWidth: 1000,
      margin: "0 auto",
      alignItems: "start"
    }
  }, /*#__PURE__*/React.createElement("nav", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 4,
      position: "sticky",
      top: 0
    }
  }, panes.map(NavRow)), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 18
    }
  }, pane === "profile" && /*#__PURE__*/React.createElement(Card, {
    padding: 28,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement(SectionHead, {
    title: "Profile",
    sub: "How you appear across the workspace"
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 16,
      marginBottom: 22
    }
  }, /*#__PURE__*/React.createElement(Avatar, {
    name: name,
    size: 64
  }), /*#__PURE__*/React.createElement(Button, {
    variant: "subtle",
    size: "sm"
  }, "Change photo")), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: 16
    }
  }, /*#__PURE__*/React.createElement(Input, {
    label: "Full name",
    value: name,
    onChange: e => setName(e.target.value),
    fill: "plain"
  }), /*#__PURE__*/React.createElement(Input, {
    label: "Work email",
    value: email,
    onChange: e => setEmail(e.target.value),
    fill: "plain"
  }), /*#__PURE__*/React.createElement(Input, {
    label: "Role",
    value: "CMO",
    fill: "plain",
    readOnly: true
  }), /*#__PURE__*/React.createElement(Input, {
    label: "Team",
    value: "Northwind Labs",
    fill: "plain",
    readOnly: true
  })), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      gap: 10,
      marginTop: 22
    }
  }, /*#__PURE__*/React.createElement(Button, {
    variant: "primary",
    size: "sm"
  }, "Save changes"), /*#__PURE__*/React.createElement(Button, {
    variant: "ghost",
    size: "sm"
  }, "Cancel"))), pane === "workspace" && /*#__PURE__*/React.createElement(Card, {
    padding: 28,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement(SectionHead, {
    title: "Workspace",
    sub: "Northwind Labs \xB7 14 members"
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: 16
    }
  }, /*#__PURE__*/React.createElement(Input, {
    label: "Workspace name",
    value: "Northwind Labs",
    fill: "plain",
    readOnly: true
  }), /*#__PURE__*/React.createElement(Input, {
    label: "Industry",
    value: "B2B SaaS",
    fill: "plain",
    readOnly: true
  })), /*#__PURE__*/React.createElement("div", {
    style: {
      marginTop: 22,
      display: "flex",
      flexDirection: "column",
      gap: 14
    }
  }, [["Reporting currency", "USD ($)"], ["Fiscal year start", "January"], ["Default attribution", "Data-driven"]].map(([l, v]) => /*#__PURE__*/React.createElement("div", {
    key: l,
    style: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "12px 0",
      borderTop: "1px solid var(--border-subtle)"
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      fontSize: "var(--text-sm)",
      color: "var(--text-secondary)"
    }
  }, l), /*#__PURE__*/React.createElement(Badge, {
    tone: "neutral"
  }, v))))), pane === "notifications" && /*#__PURE__*/React.createElement(Card, {
    padding: 28,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement(SectionHead, {
    title: "Notifications",
    sub: "What Alfred tells you, and when"
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column"
    }
  }, [["Daily briefing", "Your 8:00 AM summary, every weekday", brief, setBrief], ["Real-time decision alerts", "The moment something needs a call", alerts, setAlerts], ["Weekly digest", "A Monday recap of the week's outcomes", digest, setDigest]].map(([t, d, val, set]) => /*#__PURE__*/React.createElement("div", {
    key: t,
    style: {
      display: "flex",
      alignItems: "center",
      gap: 16,
      padding: "16px 0",
      borderTop: "1px solid var(--border-subtle)"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      flex: 1
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      fontWeight: "var(--fw-bold)",
      color: "var(--text-primary)",
      fontSize: "var(--text-base)"
    }
  }, t), /*#__PURE__*/React.createElement("div", {
    style: {
      fontSize: "var(--text-sm)",
      color: "var(--text-muted)"
    }
  }, d)), /*#__PURE__*/React.createElement(Switch, {
    checked: val,
    onChange: set
  }))))), pane === "security" && /*#__PURE__*/React.createElement(Card, {
    padding: 28,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement(SectionHead, {
    title: "Security",
    sub: "Your data is yours, full stop"
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 14
    }
  }, [["Two-factor authentication", "Active via authenticator app", "success", "Manage"], ["Data isolation", "Logically isolated Alfred environment", "info", "View"], ["No cross-customer training", "Your data never trains shared models", "info", "Learn more"]].map(([t, d, tone, cta]) => /*#__PURE__*/React.createElement("div", {
    key: t,
    style: {
      display: "flex",
      alignItems: "center",
      gap: 14,
      padding: "14px 0",
      borderTop: "1px solid var(--border-subtle)"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      width: 38,
      height: 38,
      borderRadius: "var(--radius-md)",
      background: "var(--accent-soft)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flex: "none"
    }
  }, /*#__PURE__*/React.createElement(Icon, {
    name: "security-lock",
    root: ICN,
    size: 18,
    color: "var(--orange-500)"
  })), /*#__PURE__*/React.createElement("div", {
    style: {
      flex: 1
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      fontWeight: "var(--fw-bold)",
      color: "var(--text-primary)",
      fontSize: "var(--text-base)"
    }
  }, t), /*#__PURE__*/React.createElement("div", {
    style: {
      fontSize: "var(--text-sm)",
      color: "var(--text-muted)"
    }
  }, d)), /*#__PURE__*/React.createElement(Button, {
    variant: "subtle",
    size: "sm"
  }, cta)))))));
}
window.KpiCockpit = KpiCockpit;
window.SpendRoi = SpendRoi;
window.AlertsInbox = AlertsInbox;
window.Integrations = Integrations;
window.SettingsScreen = Settings;

/* function declarations, global as they were under the browser compiler */
window.Sparkline = Sparkline;
window.KpiCockpit = KpiCockpit;
window.SpendRoi = SpendRoi;
window.AlertCard = AlertCard;
window.AlertsInbox = AlertsInbox;
window.Integrations = Integrations;
window.Settings = Settings;
})();
