/* GENERATED by scripts/build-kits.mjs from ui_kits/app/Screens2.jsx — do not edit. */
(function () {
/* ============================================================
   Alfred workspace — flagship product screens (part 2).
   Daily Briefing · Ask Alfred · Creative Lifecycle · AI Visibility.
   Light theme. Composed from the design-system primitives, matching
   Screens.jsx (soft cards, gradient accents, first-person voice).
   Each component is self-contained so scripts/verify-render.mjs can
   server-render it prop-less.
   ============================================================ */
const {
  Card,
  KpiCard,
  DecisionAlert,
  Badge,
  Button,
  Icon,
  Banner,
  Table,
  SignalCard,
  AgentStatus,
  BarChart,
  LineChart,
  DonutChart,
  Chip
} = window.AlfredAIDesignSystem_1ce241;
const ICN = "../../assets/icons";
const LOGO = "../../assets/logos";

/* ——— shared bits ——— */
const Head = ({
  title,
  sub,
  right
}) => /*#__PURE__*/React.createElement("div", {
  style: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 14
  }
}, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("h3", {
  style: {
    fontSize: "var(--text-h4)",
    fontWeight: "var(--fw-bold)",
    letterSpacing: "var(--ls-tight)"
  }
}, title), sub && /*#__PURE__*/React.createElement("div", {
  style: {
    fontSize: "var(--text-sm)",
    color: "var(--text-muted)",
    marginTop: 2
  }
}, sub)), right && /*#__PURE__*/React.createElement("div", {
  style: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 10
  }
}, right));
const SendGlyph = ({
  size = 15
}) => /*#__PURE__*/React.createElement("svg", {
  width: size,
  height: size,
  viewBox: "0 0 24 24",
  fill: "none",
  stroke: "currentColor",
  strokeWidth: "1.8",
  strokeLinecap: "round",
  strokeLinejoin: "round"
}, /*#__PURE__*/React.createElement("path", {
  d: "M4 12 21 4l-7 17-3-7-7-3Z"
}));

/* A small colored progress bar with a label — used where the bundle ProgressBar's
   gradient/plain tones aren't expressive enough (severity reds/ambers/greens). */
function MeterRow({
  label,
  value,
  color,
  suffix = "%"
}) {
  return /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      justifyContent: "space-between",
      marginBottom: 6,
      fontSize: "var(--text-xs)"
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      color: "var(--text-muted)"
    }
  }, label), /*#__PURE__*/React.createElement("span", {
    style: {
      fontWeight: "var(--fw-bold)",
      color,
      fontVariantNumeric: "tabular-nums"
    }
  }, value, suffix)), /*#__PURE__*/React.createElement("div", {
    style: {
      height: 8,
      background: "var(--gray-100)",
      borderRadius: "var(--radius-pill)",
      overflow: "hidden"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      width: `${value}%`,
      height: "100%",
      background: color,
      borderRadius: "var(--radius-pill)"
    }
  })));
}

/* ======================= DAILY BRIEFING ======================= */
function DailyBrief() {
  return /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 22,
      maxWidth: 1180,
      margin: "0 auto"
    }
  }, /*#__PURE__*/React.createElement(Card, {
    tone: "ink",
    radius: "var(--radius-2xl)",
    padding: 30,
    style: {
      position: "relative",
      overflow: "hidden"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      position: "absolute",
      inset: 0,
      background: "var(--glow-orange)",
      opacity: 0.6
    }
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      position: "relative"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 12,
      flexWrap: "wrap"
    }
  }, /*#__PURE__*/React.createElement(Badge, {
    tone: "brand",
    dot: true
  }, "Daily briefing \xB7 8:00 AM"), /*#__PURE__*/React.createElement("span", {
    style: {
      color: "rgba(255,255,255,0.6)",
      fontSize: "var(--text-xs)"
    }
  }, "Tuesday, 11 June \xB7 90-second read")), /*#__PURE__*/React.createElement("h2", {
    style: {
      color: "#fff",
      fontSize: "var(--text-h2)",
      fontWeight: "var(--fw-semibold)",
      margin: "14px 0 10px",
      letterSpacing: "var(--ls-tight)",
      maxWidth: 840,
      lineHeight: 1.15
    }
  }, "Good morning, Priya. Spend is pacing 6% hot \u2014 but ROAS climbed to 4.8x and pipeline is up 19%."), /*#__PURE__*/React.createElement("p", {
    style: {
      color: "var(--periwinkle-200)",
      fontSize: "var(--text-lg)",
      lineHeight: "var(--lh-relaxed)",
      maxWidth: 840,
      margin: 0
    }
  }, "Paid social carried 38% of pipeline this week. Two reallocations are worth an estimated", /*#__PURE__*/React.createElement("strong", {
    style: {
      color: "#fff"
    }
  }, " +$48K in revenue"), ", and three creatives are entering fatigue before the numbers show it. I've drafted every action below \u2014 you'll spend more time deciding than reading."), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      gap: 12,
      marginTop: 20,
      flexWrap: "wrap"
    }
  }, /*#__PURE__*/React.createElement(Button, {
    variant: "primary",
    size: "md"
  }, "Review 2 decisions"), /*#__PURE__*/React.createElement(Button, {
    variant: "ghost",
    size: "md",
    style: {
      color: "#fff"
    }
  }, "Listen to the brief")))), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement(Head, {
    title: "While you were away",
    sub: "What moved overnight, ranked by impact",
    right: /*#__PURE__*/React.createElement(Badge, {
      tone: "neutral"
    }, "Synced 6:02 AM")
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "repeat(4, 1fr)",
      gap: 16
    }
  }, /*#__PURE__*/React.createElement(KpiCard, {
    label: "Blended ROAS",
    value: "4.8x",
    delta: "+12.4%",
    direction: "up",
    caption: "vs last 30d",
    icon: "trend-up",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Pipeline created",
    value: "$2.68M",
    delta: "+19.5%",
    direction: "up",
    caption: "this quarter",
    icon: "trend-up",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Wasted spend",
    value: "$11.4K",
    delta: "-31%",
    direction: "down",
    valence: "good",
    caption: "I reclaimed",
    icon: "trend-down",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Spend pacing",
    value: "106%",
    delta: "+6.0%",
    direction: "flat",
    caption: "of monthly plan",
    icon: "budget",
    iconRoot: ICN
  }))), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "1.6fr 1fr",
      gap: 22,
      alignItems: "start"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 14
    }
  }, /*#__PURE__*/React.createElement(Head, {
    title: "Needs a decision today",
    sub: "I've drafted each \u2014 approve and I'll execute"
  }), /*#__PURE__*/React.createElement(DecisionAlert, {
    priority: "high",
    time: "overnight",
    iconRoot: ICN,
    title: "Google Ads brand campaign will cap out in 4 days",
    insight: "At current pacing the brand campaign exhausts its monthly budget by Saturday, leaving non-brand uncovered into the weekend. I'd move $18K to Performance Max to hold coverage.",
    action: "Reallocate $18K"
  }), /*#__PURE__*/React.createElement(DecisionAlert, {
    priority: "opportunity",
    time: "overnight",
    iconRoot: ICN,
    title: "LinkedIn CPL fell 22% on the new ABM audience",
    insight: "Cost-per-lead dropped sharply and is holding. Scaling spend +30% while efficiency lasts is worth an estimated +$30K in pipeline this month.",
    action: "Scale +30%"
  }), /*#__PURE__*/React.createElement(DecisionAlert, {
    priority: "medium",
    time: "overnight",
    iconRoot: ICN,
    title: "Three Meta creatives are entering fatigue",
    insight: "Frequency crossed 3.0 and CTR is down 14% over seven days in the 25\u201334 segment. I've queued refreshes from your creative library for approval.",
    action: "Approve refreshes"
  })), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 22
    }
  }, /*#__PURE__*/React.createElement(Card, {
    padding: 22,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement(Head, {
    title: "Steady \u2014 no action needed"
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 12
    }
  }, /*#__PURE__*/React.createElement(SignalCard, {
    tone: "action",
    label: "Holding",
    statement: "Email open rate held at 41%",
    trace: "Subject-line test concluded; I'll keep watching the next send."
  }), /*#__PURE__*/React.createElement(SignalCard, {
    tone: "truth",
    label: "Reconciled",
    statement: "GA4 and HubSpot agree on attribution",
    trace: "No discrepancy this cycle \u2014 your board numbers will match."
  }))), /*#__PURE__*/React.createElement(Card, {
    tone: "surface",
    padding: 22,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      fontWeight: "var(--fw-bold)",
      fontSize: "var(--text-base)",
      color: "var(--text-primary)",
      marginBottom: 6
    }
  }, "Delivered the way you read"), /*#__PURE__*/React.createElement("div", {
    style: {
      fontSize: "var(--text-sm)",
      color: "var(--text-secondary)",
      lineHeight: "var(--lh-normal)",
      marginBottom: 14
    }
  }, "This brief reaches you at 8:00 AM on email, Slack, and in-app \u2014 every weekday."), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      gap: 8,
      flexWrap: "wrap"
    }
  }, ["Email", "Slack", "In-app"].map(c => /*#__PURE__*/React.createElement("span", {
    key: c,
    style: {
      padding: "5px 12px",
      borderRadius: "var(--radius-pill)",
      background: "var(--accent-soft)",
      color: "var(--text-on-tint-brand)",
      fontSize: "var(--text-xs)",
      fontWeight: "var(--fw-bold)"
    }
  }, c)))))));
}

/* ======================= SEEK ALFRED ======================= */
function SeekAlfred() {
  const [q, setQ] = React.useState("Why did CAC rise last week?");
  const chips = ["Forecast Q3 pipeline", "Which channel is underspending?", "What's my most efficient campaign?", "How is AI visibility trending?"];
  const follow = ["Break this down by week", "What would fixing it cost?", "Draft the reallocation"];
  return /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 22,
      maxWidth: 1180,
      margin: "0 auto"
    }
  }, /*#__PURE__*/React.createElement(Card, {
    padding: 20,
    shadow: "sm",
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 14
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 10
    }
  }, /*#__PURE__*/React.createElement("img", {
    src: `${LOGO}/alfred-icon.svg`,
    alt: "",
    style: {
      height: 26
    }
  }), /*#__PURE__*/React.createElement("span", {
    style: {
      fontWeight: "var(--fw-bold)",
      fontSize: "var(--text-base)"
    }
  }, "Ask Alfred"), /*#__PURE__*/React.createElement(Badge, {
    tone: "info"
  }, "on-demand \xB7 grounded in your data")), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 10,
      padding: "6px 6px 6px 18px",
      background: "var(--gray-50)",
      border: "1px solid var(--border-subtle)",
      borderRadius: "var(--radius-pill)"
    }
  }, /*#__PURE__*/React.createElement("input", {
    value: q,
    onChange: e => setQ(e.target.value),
    placeholder: "Ask anything about your marketing performance\u2026",
    style: {
      flex: 1,
      border: "none",
      background: "transparent",
      fontFamily: "var(--font-sans)",
      fontSize: "var(--text-base)",
      color: "var(--text-primary)"
    }
  }), /*#__PURE__*/React.createElement(Button, {
    variant: "subtle",
    size: "sm",
    iconRight: /*#__PURE__*/React.createElement(SendGlyph, null)
  }, "Ask")), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      gap: 8,
      flexWrap: "wrap"
    }
  }, chips.map(c => /*#__PURE__*/React.createElement(Chip, {
    key: c,
    onClick: () => setQ(c)
  }, c)))), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "1.6fr 1fr",
      gap: 22,
      alignItems: "start"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 16
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      justifyContent: "flex-end"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      background: "var(--orange-50)",
      color: "var(--text-primary)",
      padding: "10px 16px",
      borderRadius: "var(--radius-xl)",
      fontSize: "var(--text-base)",
      fontWeight: "var(--fw-medium)",
      maxWidth: 460
    }
  }, "Why did CAC rise last week?")), /*#__PURE__*/React.createElement(Card, {
    padding: 24,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 10,
      marginBottom: 14
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      width: 30,
      height: 30,
      borderRadius: "var(--radius-md)",
      background: "var(--gradient-brand)",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center"
    }
  }, /*#__PURE__*/React.createElement("img", {
    src: `${LOGO}/alfred-icon-white.svg`,
    alt: "",
    style: {
      height: 17
    }
  })), /*#__PURE__*/React.createElement("span", {
    style: {
      fontWeight: "var(--fw-bold)",
      fontSize: "var(--text-base)"
    }
  }, "Alfred"), /*#__PURE__*/React.createElement(Badge, {
    tone: "success",
    dot: true
  }, "answered in 4s")), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: "var(--text-lg)",
      lineHeight: "var(--lh-relaxed)",
      color: "var(--text-primary)",
      margin: "0 0 16px"
    }
  }, "Blended CAC rose ", /*#__PURE__*/React.createElement("strong", null, "8% to $184"), " last week, and it's almost entirely one channel: ", /*#__PURE__*/React.createElement("strong", null, "Meta"), ". Creative fatigue in the 25\u201334 segment pushed frequency past 3.0, so CTR fell 14% and you paid more for the same conversions. Search and LinkedIn CAC actually improved."), /*#__PURE__*/React.createElement(Card, {
    tone: "sunken",
    shadow: "none",
    padding: 18,
    style: {
      marginBottom: 16
    }
  }, /*#__PURE__*/React.createElement(Head, {
    title: "CAC by channel \xB7 last 7 days"
  }), /*#__PURE__*/React.createElement(BarChart, {
    height: 150,
    data: [{
      label: "Meta",
      value: 248,
      display: "$248",
      color: "var(--orange-500)"
    }, {
      label: "Search",
      value: 142,
      display: "$142",
      color: "var(--periwinkle-400)"
    }, {
      label: "LinkedIn",
      value: 196,
      display: "$196",
      color: "var(--periwinkle-500)"
    }, {
      label: "YouTube",
      value: 320,
      display: "$320",
      color: "var(--orange-300)"
    }, {
      label: "Blended",
      value: 184,
      display: "$184"
    }]
  })), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: "var(--text-base)",
      lineHeight: "var(--lh-relaxed)",
      color: "var(--text-body)",
      margin: "0 0 18px"
    }
  }, "Refreshing the three fatigued Meta creatives should pull Meta CAC back toward $205 within a week, recovering an estimated ", /*#__PURE__*/React.createElement("strong", null, "$9K"), " in efficiency this month."), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      gap: 10,
      flexWrap: "wrap"
    }
  }, /*#__PURE__*/React.createElement(Button, {
    variant: "primary",
    size: "sm"
  }, "Queue creative refreshes"), /*#__PURE__*/React.createElement(Button, {
    variant: "subtle",
    size: "sm"
  }, "Open Creative Lifecycle"))), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      gap: 8,
      flexWrap: "wrap"
    }
  }, follow.map(c => /*#__PURE__*/React.createElement(Chip, {
    key: c
  }, c)))), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 18
    }
  }, /*#__PURE__*/React.createElement(AgentStatus, {
    query: "Why did CAC rise last week?",
    activeStep: 4,
    autoplay: false,
    footer: "Reasoned across 4 sources \xB7 14 months of history",
    steps: ["Pulled CAC by channel", "Correlated with creative frequency", "Isolated the 25–34 segment", "Modelled the recovery"]
  }), /*#__PURE__*/React.createElement(Card, {
    padding: 20,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement(Head, {
    title: "Sources",
    sub: "What grounded this answer"
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 12
    }
  }, [["Meta Ads", "creative · frequency · CTR"], ["GA4", "sessions · conversions"], ["HubSpot", "CAC · pipeline"], ["Google Ads", "search CAC"]].map(([n, d]) => /*#__PURE__*/React.createElement("div", {
    key: n,
    style: {
      display: "flex",
      alignItems: "center",
      gap: 12
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      width: 8,
      height: 8,
      borderRadius: "50%",
      background: "var(--success-500)",
      flex: "none"
    }
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      flex: 1,
      minWidth: 0
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      fontSize: "var(--text-sm)",
      fontWeight: "var(--fw-bold)",
      color: "var(--text-primary)"
    }
  }, n), /*#__PURE__*/React.createElement("div", {
    style: {
      fontSize: "var(--text-xs)",
      color: "var(--text-muted)"
    }
  }, d)), /*#__PURE__*/React.createElement(Badge, {
    tone: "success",
    dot: true
  }, "live"))))))));
}

/* ======================= CREATIVE LIFECYCLE ======================= */
function CreativeLifecycle() {
  const creatives = [{
    name: "Spring Launch — Hero A",
    ch: "Meta",
    freq: "3.4",
    fatigue: 86,
    ctr: "-18%",
    rec: "Refresh",
    tone: "danger"
  }, {
    name: "ABM Carousel — Tier 1",
    ch: "LinkedIn",
    freq: "2.1",
    fatigue: 38,
    ctr: "+4%",
    rec: "Keep live",
    tone: "success"
  }, {
    name: "Retargeting — Testimonial",
    ch: "Meta",
    freq: "3.1",
    fatigue: 72,
    ctr: "-12%",
    rec: "Rotate",
    tone: "warning"
  }, {
    name: "PMax — Asset Group 2",
    ch: "Google",
    freq: "2.6",
    fatigue: 54,
    ctr: "-6%",
    rec: "Rotate",
    tone: "warning"
  }, {
    name: "Brand Film — 15s",
    ch: "YouTube",
    freq: "1.4",
    fatigue: 22,
    ctr: "+1%",
    rec: "Keep live",
    tone: "success"
  }, {
    name: "Promo — Static B",
    ch: "Meta",
    freq: "3.6",
    fatigue: 91,
    ctr: "-21%",
    rec: "Pause",
    tone: "danger"
  }];
  const sev = f => f >= 75 ? "var(--danger-500)" : f >= 50 ? "var(--orange-500)" : "var(--success-500)";
  /* Quiet, deterministic platform-coded tints — the fatigue meter stays the loudest element on each card. */
  const platformTint = {
    Meta: "var(--periwinkle-100)",
    LinkedIn: "var(--periwinkle-50)",
    Google: "var(--orange-50)",
    YouTube: "var(--orange-100)",
    TikTok: "var(--gray-100)"
  };
  return /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 22,
      maxWidth: 1180,
      margin: "0 auto"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "repeat(4, 1fr)",
      gap: 16
    }
  }, /*#__PURE__*/React.createElement(KpiCard, {
    label: "Creatives live",
    value: "24",
    delta: "+3",
    direction: "flat",
    caption: "across 4 channels",
    icon: "channel-mix",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Entering fatigue",
    value: "3",
    delta: "+2",
    direction: "up",
    valence: "bad",
    caption: "frequency > 3.0",
    icon: "alert-warning",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Avg. frequency",
    value: "2.8",
    delta: "+0.4",
    direction: "flat",
    caption: "last 7 days",
    icon: "trend-up",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "CTR (7-day)",
    value: "1.9%",
    delta: "-9.0%",
    direction: "down",
    caption: "blended",
    icon: "trend-down",
    iconRoot: ICN
  })), /*#__PURE__*/React.createElement(Banner, {
    tone: "warning",
    title: "Three creatives crossed the frequency-3.0 threshold in the 25\u201334 segment",
    action: /*#__PURE__*/React.createElement(Button, {
      variant: "subtle",
      size: "sm"
    }, "Queue all refreshes")
  }, "I caught this before it showed in aggregate CTR. Refreshing now recovers an estimated $9K in efficiency this month \u2014 your spend hasn't noticed the fatigue yet, but I have."), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement(Head, {
    title: "Creative library",
    sub: "Asset-level fatigue, scored continuously",
    right: /*#__PURE__*/React.createElement(Badge, {
      tone: "neutral"
    }, "Updated 11m ago")
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "repeat(3, 1fr)",
      gap: 16
    }
  }, creatives.map(c => /*#__PURE__*/React.createElement(Card, {
    key: c.name,
    interactive: true,
    padding: 0,
    shadow: "sm",
    style: {
      overflow: "hidden",
      display: "flex",
      flexDirection: "column"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      height: 92,
      background: platformTint[c.ch] || "var(--gray-100)",
      position: "relative",
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "flex-end",
      padding: 12
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      position: "relative",
      padding: "4px 10px",
      borderRadius: "var(--radius-pill)",
      background: "rgba(255,255,255,0.92)",
      color: "var(--ink-800)",
      fontSize: "var(--text-2xs)",
      fontWeight: "var(--fw-bold)",
      letterSpacing: "var(--ls-caps)",
      textTransform: "uppercase"
    }
  }, c.ch)), /*#__PURE__*/React.createElement("div", {
    style: {
      padding: 16,
      display: "flex",
      flexDirection: "column",
      gap: 12
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      fontWeight: "var(--fw-bold)",
      color: "var(--text-primary)",
      fontSize: "var(--text-base)"
    }
  }, c.name), /*#__PURE__*/React.createElement(MeterRow, {
    label: "Fatigue",
    value: c.fatigue,
    color: sev(c.fatigue)
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      justifyContent: "space-between",
      fontSize: "var(--text-sm)",
      color: "var(--text-secondary)"
    }
  }, /*#__PURE__*/React.createElement("span", null, "Frequency ", /*#__PURE__*/React.createElement("strong", {
    style: {
      color: "var(--text-primary)"
    }
  }, c.freq)), /*#__PURE__*/React.createElement("span", null, "CTR ", /*#__PURE__*/React.createElement("strong", {
    style: {
      color: c.ctr.startsWith("-") ? "var(--danger-500)" : "var(--success-500)"
    }
  }, c.ctr))), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      borderTop: "1px solid var(--border-subtle)",
      paddingTop: 12
    }
  }, /*#__PURE__*/React.createElement(Badge, {
    tone: c.tone,
    dot: true
  }, c.rec), /*#__PURE__*/React.createElement(Button, {
    variant: "subtle",
    size: "sm",
    style: {
      marginLeft: "auto"
    }
  }, "Review"))))))), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "1.5fr 1fr",
      gap: 22,
      alignItems: "start"
    }
  }, /*#__PURE__*/React.createElement(Card, {
    padding: 24,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement(Head, {
    title: "Engagement decay \u2014 Spring Launch Hero A",
    sub: "CTR index, last 7 weeks"
  }), /*#__PURE__*/React.createElement(LineChart, {
    height: 170,
    points: [100, 98, 94, 88, 79, 71, 64],
    labels: ["W1", "W2", "W3", "W4", "W5", "W6", "W7"]
  })), /*#__PURE__*/React.createElement(Card, {
    tone: "ink",
    padding: 24,
    radius: "var(--radius-2xl)",
    style: {
      position: "relative",
      overflow: "hidden"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      position: "absolute",
      inset: 0,
      background: "var(--glow-orange)",
      opacity: 0.5
    }
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      position: "relative"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 10,
      marginBottom: 12
    }
  }, /*#__PURE__*/React.createElement("img", {
    src: `${LOGO}/alfred-icon-white.svg`,
    alt: "",
    style: {
      height: 22
    }
  }), /*#__PURE__*/React.createElement("span", {
    style: {
      color: "#fff",
      fontWeight: "var(--fw-bold)",
      fontSize: "var(--text-base)"
    }
  }, "My recommendation")), /*#__PURE__*/React.createElement("p", {
    style: {
      color: "var(--periwinkle-200)",
      fontSize: "var(--text-base)",
      lineHeight: "var(--lh-relaxed)",
      margin: "0 0 16px"
    }
  }, "Pause ", /*#__PURE__*/React.createElement("strong", {
    style: {
      color: "#fff"
    }
  }, "Promo \u2014 Static B"), " now and refresh the two Spring Launch assets within 48 hours. The audience has seen them 3.6 times on average; another week at this frequency costs roughly", /*#__PURE__*/React.createElement("strong", {
    style: {
      color: "#fff"
    }
  }, " $9K"), " in lost efficiency."), /*#__PURE__*/React.createElement(Button, {
    variant: "primary",
    size: "sm",
    fullWidth: true
  }, "Approve plan")))));
}

/* ======================= AI VISIBILITY ======================= */
function AiVisibility() {
  const engines = [{
    name: "ChatGPT",
    score: 82,
    note: "Cited in 82% of category prompts",
    tone: "var(--success-500)"
  }, {
    name: "Perplexity",
    score: 74,
    note: "Cited, usually as a secondary source",
    tone: "var(--success-500)"
  }, {
    name: "Google AI Overviews",
    score: 61,
    note: "Appears for branded queries",
    tone: "var(--orange-500)"
  }, {
    name: "Claude",
    score: 57,
    note: "Mentioned, not always linked",
    tone: "var(--orange-500)"
  }, {
    name: "Gemini",
    score: 38,
    note: "Rarely surfaced in answers",
    tone: "var(--danger-500)"
  }];
  const fixCols = [{
    key: "fix",
    header: "Recommended fix"
  }, {
    key: "impact",
    header: "Impact",
    align: "right",
    render: v => /*#__PURE__*/React.createElement(Badge, {
      tone: v === "High" ? "brand" : "info"
    }, v)
  }, {
    key: "effort",
    header: "Effort",
    align: "right",
    render: v => /*#__PURE__*/React.createElement(Badge, {
      tone: v === "Low" ? "success" : v === "Med" ? "warning" : "danger"
    }, v)
  }];
  const fixRows = [{
    fix: "Add Product & FAQ schema to /platform",
    impact: "High",
    effort: "Low"
  }, {
    fix: "Earn 3 citations on AI-ranked comparison sites",
    impact: "High",
    effort: "Med"
  }, {
    fix: "Fix 4 factual inconsistencies in llms.txt",
    impact: "Med",
    effort: "Low"
  }, {
    fix: "Strengthen authority for ‘decision intelligence’",
    impact: "Med",
    effort: "High"
  }];
  return /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 22,
      maxWidth: 1180,
      margin: "0 auto"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "1fr 1.5fr",
      gap: 22,
      alignItems: "stretch"
    }
  }, /*#__PURE__*/React.createElement(Card, {
    padding: 24,
    shadow: "sm",
    style: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: 16,
      justifyContent: "center"
    }
  }, /*#__PURE__*/React.createElement(DonutChart, {
    size: 184,
    thickness: 20,
    centerLabel: "72",
    centerSub: "out of 100",
    segments: [{
      label: "Score",
      value: 72,
      color: "var(--orange-500)"
    }, {
      label: "Gap",
      value: 28,
      color: "transparent"
    }]
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      alignItems: "center",
      gap: 10
    }
  }, /*#__PURE__*/React.createElement(Badge, {
    tone: "success",
    dot: true
  }, "+9 vs last month"), /*#__PURE__*/React.createElement(Badge, {
    tone: "neutral"
  }, "Top 3 in category"))), /*#__PURE__*/React.createElement(Card, {
    tone: "gradient",
    padding: 28,
    style: {
      position: "relative",
      overflow: "hidden",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      color: "var(--ink-900)"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      fontSize: "var(--text-2xs)",
      fontWeight: "var(--fw-bold)",
      letterSpacing: "var(--ls-caps)",
      textTransform: "uppercase",
      opacity: 0.9,
      marginBottom: 10
    }
  }, "AI visibility score \xB7 unique to Alfred"), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: "var(--text-h4)",
      fontWeight: "var(--fw-semibold)",
      lineHeight: 1.3,
      margin: "0 0 14px",
      letterSpacing: "var(--ls-tight)"
    }
  }, "Your buyers are asking AI which marketing platform to use. Right now you're the answer 72% of the time."), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: "var(--text-base)",
      lineHeight: "var(--lh-relaxed)",
      opacity: 0.95,
      margin: 0
    }
  }, "You're strong on ChatGPT and Perplexity but barely surface on Gemini. The three fixes I've prioritised would lift you to an estimated ", /*#__PURE__*/React.createElement("strong", null, "81"), " within a quarter.")))), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "repeat(4, 1fr)",
      gap: 16
    }
  }, /*#__PURE__*/React.createElement(KpiCard, {
    label: "Citation rate",
    value: "68%",
    delta: "+11%",
    direction: "up",
    caption: "in AI answers",
    icon: "trend-up",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Structured-data",
    value: "74%",
    delta: "+6%",
    direction: "up",
    caption: "schema completeness",
    icon: "web-clarity",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Share of voice",
    value: "22%",
    delta: "+3%",
    direction: "up",
    caption: "vs 6 competitors",
    icon: "channel-mix",
    iconRoot: ICN
  }), /*#__PURE__*/React.createElement(KpiCard, {
    label: "Factual accuracy",
    value: "91%",
    delta: "-2%",
    direction: "flat",
    caption: "of AI claims correct",
    icon: "audit-log",
    iconRoot: ICN
  })), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: 22,
      alignItems: "start"
    }
  }, /*#__PURE__*/React.createElement(Card, {
    padding: 24,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement(Head, {
    title: "Where you're cited",
    sub: "Presence across AI answer engines"
  }), /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      flexDirection: "column",
      gap: 16
    }
  }, engines.map(e => /*#__PURE__*/React.createElement("div", {
    key: e.name
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "baseline",
      marginBottom: 6
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      fontSize: "var(--text-sm)",
      fontWeight: "var(--fw-bold)",
      color: "var(--text-primary)"
    }
  }, e.name), /*#__PURE__*/React.createElement("span", {
    style: {
      fontSize: "var(--text-xs)",
      color: "var(--text-muted)"
    }
  }, e.note)), /*#__PURE__*/React.createElement("div", {
    style: {
      height: 8,
      background: "var(--gray-100)",
      borderRadius: "var(--radius-pill)",
      overflow: "hidden"
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      width: `${e.score}%`,
      height: "100%",
      background: e.tone,
      borderRadius: "var(--radius-pill)"
    }
  })))))), /*#__PURE__*/React.createElement(Card, {
    padding: 24,
    shadow: "sm"
  }, /*#__PURE__*/React.createElement(Head, {
    title: "Prioritised fixes",
    sub: "Ranked by impact, then effort",
    right: /*#__PURE__*/React.createElement(Button, {
      variant: "subtle",
      size: "sm"
    }, "Export")
  }), /*#__PURE__*/React.createElement(Table, {
    columns: fixCols,
    rows: fixRows
  }))));
}
window.DailyBrief = DailyBrief;
window.SeekAlfred = SeekAlfred;
window.CreativeLifecycle = CreativeLifecycle;
window.AiVisibility = AiVisibility;

/* function declarations, global as they were under the browser compiler */
window.MeterRow = MeterRow;
window.DailyBrief = DailyBrief;
window.SeekAlfred = SeekAlfred;
window.CreativeLifecycle = CreativeLifecycle;
window.AiVisibility = AiVisibility;
})();
