/* Build the publishable npm package into dist/.

   The global `_ds_bundle.js` is right for the preview pages and the
   claude.ai/design runtime, but it is an IIFE that assigns to `window` and
   expects React as a global — you cannot `import` it. This emits a real ESM
   module from the SAME compile pipeline (scripts/compile-components.mjs), so
   the published package can't drift from the bundle every verifier tests.

   Two details that matter:
   - Each component is wrapped in its own IIFE returning its exports. Component
     files declare top-level helpers (two of them both declare `PALETTE`), so
     concatenating them at module scope would be a redeclaration error.
   - React is a peerDependency, not a bundled one. Two Reacts in one app breaks
     hooks, so the consumer's copy must be the only copy.

   dist/ is generated, not committed — `verify-npm.mjs` rebuilds and checks it.
   Publishing is a human step: `npm publish dist` (see readme).

   Run: node scripts/build-npm.mjs */
import fs from "node:fs";
import path from "node:path";
import { compileComponents } from "./compile-components.mjs";

const ROOT = path.resolve(new URL("..", import.meta.url).pathname);
const DIST = path.join(ROOT, "dist");
const PKG_NAME = "@alfredai/design-system";
const VERSION = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8")).dsVersion;
if (!VERSION) throw new Error("package.json is missing `dsVersion` — the published package's semver");

const { ordered } = await compileComponents(ROOT);
const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, "_ds_manifest.json"), "utf8"));
const publicNames = manifest.components.map((c) => c.name);

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });

/* —— dist/index.mjs ————————————————————————————————————————————————————— */
const blocks = ordered.map((p) => {
  const deps = p.deps.filter((d) => ordered.some((o) => o.names.includes(d)));
  // deps are module-scope consts already defined above (topological order)
  const ret = `return { ${p.names.join(", ")} };`;
  const body = `${p.code}\n${ret}`;
  return `// ${p.rel}\nconst { ${p.names.join(", ")} } = (() => {\n${body}\n})();`;
});
const esm = `/* ${PKG_NAME} v${VERSION}
   Generated by scripts/build-npm.mjs — do not edit.
   Every component from the Alfred AI design system, as ES modules.
   Pair with the stylesheet: import "${PKG_NAME}/styles.css"; */
import React from "react";

${blocks.join("\n\n")}

export { ${publicNames.join(", ")} };
`;
fs.writeFileSync(path.join(DIST, "index.mjs"), esm);

/* —— dist/index.d.ts — re-export each component's authored types ————————— */
const typeLines = manifest.components.map((c) => {
  const rel = c.sourcePath.replace(/\.jsx$/, "");
  return `export type { ${c.name}Props } from "./types/${rel.replace(/^components\//, "")}";\nexport { ${c.name} } from "./types/${rel.replace(/^components\//, "")}";`;
});
// copy the .d.ts tree so the re-exports resolve
const copyTypes = (dir, into) => {
  fs.mkdirSync(into, { recursive: true });
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const from = path.join(dir, e.name);
    if (e.isDirectory()) copyTypes(from, path.join(into, e.name));
    else if (e.name.endsWith(".d.ts")) fs.copyFileSync(from, path.join(into, e.name));
  }
};
copyTypes(path.join(ROOT, "components"), path.join(DIST, "types"));
fs.writeFileSync(path.join(DIST, "index.d.ts"),
  `/* ${PKG_NAME} v${VERSION} — generated. */\n${typeLines.join("\n")}\n`);

/* —— styles, tokens, fonts, icons, logos ————————————————————————————————
   styles.css is import-only, so the token CSS and @font-face files have to come
   with it or the type system silently falls back to system fonts. */
const copy = (rel) => {
  const from = path.join(ROOT, rel), to = path.join(DIST, rel);
  if (!fs.existsSync(from)) return;
  if (fs.statSync(from).isDirectory()) {
    fs.mkdirSync(to, { recursive: true });
    for (const e of fs.readdirSync(from)) copy(path.join(rel, e));
  } else {
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
  }
};
copy("styles.css");
copy("tokens");
copy("assets/fonts");
copy("assets/icons");
copy("assets/logos");

/* —— dist/package.json ——————————————————————————————————————————————————
   Generated rather than published from the repo root: the root manifest is the
   dev-tooling one (private, 30-odd verifier scripts) and has no business in a
   consumer's node_modules. */
const pkg = {
  name: PKG_NAME,
  version: VERSION,
  description: "Alfred AI design system — tokens, themes and 115 React components.",
  license: "SEE LICENSE IN LICENSE",
  type: "module",
  main: "./index.mjs",
  module: "./index.mjs",
  types: "./index.d.ts",
  exports: {
    ".": { types: "./index.d.ts", import: "./index.mjs" },
    "./styles.css": "./styles.css",
    "./tokens/*": "./tokens/*",
    "./assets/*": "./assets/*",
    "./package.json": "./package.json",
  },
  sideEffects: ["*.css"],
  /* Scoped packages default to RESTRICTED on npm, so a scoped publish without
     this silently ships private and every `npm i` 404s for everyone else.
     Baked in rather than relying on remembering `--access public`. */
  publishConfig: { access: "public" },
  peerDependencies: { react: ">=18", "react-dom": ">=18" },
  repository: { type: "git", url: "git+https://github.com/raghavmkarya/alfred-design-system.git" },
  homepage: "https://raghavmkarya.github.io/alfred-design-system/",
  files: ["index.mjs", "index.d.ts", "types", "styles.css", "tokens", "assets", "readme.md"],
};
fs.writeFileSync(path.join(DIST, "package.json"), JSON.stringify(pkg, null, 2) + "\n");

/* —— dist/readme.md — what a consumer needs, not the contributor readme —— */
fs.writeFileSync(path.join(DIST, "readme.md"), `# ${PKG_NAME}

Tokens, themes and ${publicNames.length} React components from the Alfred AI design system.

\`\`\`bash
npm i ${PKG_NAME} react react-dom
\`\`\`

\`\`\`jsx
import { Button, KpiCard } from "${PKG_NAME}";
import "${PKG_NAME}/styles.css";          // tokens + @font-face closure, import once

<KpiCard label="Blended ROAS" value="4.8x" delta="+12.4%" direction="up" />
\`\`\`

## Themes, density and direction

Everything is driven by attributes, so a subtree can differ from the page:

\`\`\`html
<html data-theme="dark">          <!-- light (default) | app-dark | dark -->
<section data-density="compact">  <!-- compact | comfortable (default) | spacious -->
<div dir="rtl">                   <!-- components mirror via logical properties -->
\`\`\`

React is a **peer** dependency: two copies of React in one app breaks hooks, so
your copy is the only copy.

Browse every component live, with prop controls, at
<https://raghavmkarya.github.io/alfred-design-system/playground/>.
`);

const bytes = (function du(p) {
  const s = fs.statSync(p);
  return s.isDirectory() ? fs.readdirSync(p).reduce((n, e) => n + du(path.join(p, e)), 0) : s.size;
})(DIST);
console.log(`dist/ built — ${PKG_NAME} v${VERSION}, ${publicNames.length} components, ${(bytes / 1048576).toFixed(1)} MB`);
