/* Compile the UI-kit JSX to plain JS, so the published pages need no compiler.

   The four kit pages (app, app-dark, website, onboarding) used to load React,
   ReactDOM and `@babel/standalone` from unpkg and transform their JSX in the
   browser. Two problems with that, and only one of them is the CDN:

     1. `@babel/standalone` is **3.1MB**. Vendoring it the way the playground
        vendors React would have committed twenty times the playground's weight
        to ship a compiler to every visitor of a demo page.
     2. Compiling in the browser is work the build can do once. These pages are
        static: nothing about them is dynamic at load time.

   So every `.jsx` under `ui_kits` gets a committed `.js` twin, compiled here with
   the same `@babel/standalone` the component pipeline uses, and the pages load
   those. No Babel at runtime, no CDN, and the pages get faster.

   The output is COMMITTED and checked for freshness by `verify-playground`,
   the same contract `_ds_bundle.js` has: a deterministic rebuild must produce
   no diff, so a `.jsx` edit that is not recompiled fails CI rather than
   shipping a page that silently runs the old code.

   Run: node scripts/build-kits.mjs   (add --check to diff without writing) */
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";

const ROOT = path.resolve(new URL("..", import.meta.url).pathname);
/* ui_kits was the original surface; library/ (the inspiration pattern library)
   follows the same committed-twin contract. */
const KIT_ROOTS = ["ui_kits", "library"].map((d) => path.join(ROOT, d));
const CHECK = process.argv.includes("--check");

const babelSrc = fs.readFileSync(path.join(ROOT, "node_modules/@babel/standalone/babel.min.js"), "utf8");
const bctx = {}; bctx.window = bctx; bctx.self = bctx; vm.createContext(bctx);
vm.runInContext(babelSrc, bctx);
const Babel = bctx.Babel;

const walk = (dir) => fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
  const p = path.join(dir, e.name);
  return e.isDirectory() ? walk(p) : p.endsWith(".jsx") ? [p] : [];
});

const sources = () => KIT_ROOTS.filter(fs.existsSync).flatMap(walk).sort();

const stale = [];
let written = 0;
for (const jsx of sources()) {
  const rel = path.relative(ROOT, jsx).split(path.sep).join("/");
  const out = jsx.replace(/\.jsx$/, ".js");
  const src = fs.readFileSync(jsx, "utf8");
  const { code } = Babel.transform(src, { presets: [["react", { runtime: "classic" }]], sourceType: "script", compact: false });

  /* Each file is wrapped in an IIFE, and its top-level FUNCTION declarations
     are re-exported to `window`. That is not a style choice — it reproduces
     exactly what `<script type="text/babel">` used to do, and getting it wrong
     breaks the page in one direction or the other:

       - Babel standalone ran each block through an indirect eval, where a
         top-level `function` declaration lands on the global object but a
         top-level `const` does NOT. So the kits could each write
         `const { Badge } = window.AlfredAIDesignSystem_1ce241` privately while
         still seeing each other's components.
       - Plain <script> tags share one lexical scope. Without the wrapper, the
         second file to destructure `Badge` throws "Identifier 'Badge' has
         already been declared" and the page renders nothing. It did exactly
         that on the first attempt.

     Arrow-function components were already exported by hand (`window.X = X`);
     those lines keep working inside the wrapper. */
  const exported = [...src.matchAll(/^function\s+([A-Za-z0-9_$]+)/gm)].map((m) => m[1]);
  const tail = exported.length
    ? "\n/* function declarations, global as they were under the browser compiler */\n"
      + exported.map((n) => `window.${n} = ${n};`).join("\n") + "\n"
    : "";
  const banner = `/* GENERATED by scripts/build-kits.mjs from ${rel} — do not edit. */\n`;
  const next = `${banner}(function () {\n${code}\n${tail}})();\n`;
  const prev = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : null;
  if (prev === next) continue;
  if (CHECK) { stale.push(path.relative(ROOT, out).split(path.sep).join("/")); continue; }
  fs.writeFileSync(out, next);
  written++;
}

if (CHECK) {
  if (stale.length) {
    console.log(`FAIL stale compiled kit output — run \`node scripts/build-kits.mjs\` and commit:\n  ${stale.join("\n  ")}`);
    process.exit(1);
  }
  console.log("OK   kits        — every compiled kit file matches a clean rebuild");
} else {
  console.log(`Compiled ${written} kit file(s) changed of ${sources().length} total.`);
}
