/* Derive multi-platform token exports from the token CSS (the source of
   truth). Parses tokens/*.css, syncs the token list into _ds_manifest.json,
   then emits:
     tokens/tokens.json        — structured token tree (light + dark)
     tokens/tailwind.preset.cjs — Tailwind preset referencing the CSS vars
     tokens/framer-styles.json  — color/text styles for the Framer sync
   Run: node scripts/gen-tokens.mjs   (add --check to diff without writing)

   The outputs are COMMITTED and freshness-gated by verify-tokens.mjs. Without
   that gate a token added to the CSS ships to the site (the CSS is the runtime)
   while the manifest, Tailwind preset and Framer styles keep describing the old
   system — which is exactly what happened to the six style-absorption tokens.

   NOTE: only the files in TOKEN_FILES are scanned. A token defined in any other
   tokens/*.css file is invisible to every downstream channel. */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(new URL("..", import.meta.url).pathname);
const DARK = '[data-theme="dark"]';
const m = JSON.parse(fs.readFileSync(path.join(ROOT, "_ds_manifest.json"), "utf8"));
const CHECK = process.argv.includes("--check");
/* Collected, then written (or diffed) in one place at the end. */
const OUT = new Map();
const emit = (rel, content) => OUT.set(rel, content);

// —— parse tokens/*.css → { name, value, kind, definedIn, annotation?, scope? } ——
// Kind comes from a trailing `/* @kind … */` comment when present, else by name.
const TOKEN_FILES = ["tokens/colors.css", "tokens/typography.css", "tokens/spacing.css", "tokens/density.css", "tokens/elevation.css"];
const KIND_RULES = [
  [/^--(orange|periwinkle|ink|slate|gray|white|black|success|warning|danger|info|gradient|glow|bg-|surface|border|accent|chart-|overlay-)/, "color"],
  [/^--(text-|font-|fw-|lh-|ls-)/, "font"],
  [/^--space-/, "spacing"],
  [/^--density-/, "spacing"],
  [/^--radius-/, "radius"],
  [/^--shadow-/, "shadow"],
];
const inferKind = (name) => (KIND_RULES.find(([re]) => re.test(name)) || [null, "other"])[1];
const toks = [];
for (const rel of TOKEN_FILES) {
  const css = fs.readFileSync(path.join(ROOT, rel), "utf8");
  for (const bm of css.matchAll(/(?:^|\n)\s*(:root|\[data-theme="dark"\])\s*\{([\s\S]*?)\n\}/g)) {
    const scope = bm[1] === ":root" ? undefined : DARK;
    for (const line of bm[2].split("\n")) {
      const dm = line.match(/^\s*(--[\w-]+)\s*:\s*([^;]+);(.*)$/);
      if (!dm) continue;
      const comments = [...dm[3].matchAll(/\/\*\s*([\s\S]*?)\s*\*\//g)].map((c) => c[1]);
      let kind = null;
      const notes = [];
      for (const c of comments) {
        const k = c.match(/^@kind\s+(\w+)$/);
        if (k) kind = k[1]; else notes.push(c);
      }
      const t = { name: dm[1], value: dm[2].trim(), kind: kind || inferKind(dm[1]), definedIn: rel };
      if (notes.length) t.annotation = notes.join(" · ");
      if (scope) t.scope = scope;
      toks.push(t);
    }
  }
}
m.tokens = toks;
emit("_ds_manifest.json", JSON.stringify(m));
const base = toks.filter((t) => !t.scope);
const dark = toks.filter((t) => t.scope === DARK);
const byName = (list) => Object.fromEntries(list.map((t) => [t.name.replace(/^--/, ""), t.value]));
const pick = (list, re) => list.filter((t) => re.test(t.name));

// —— structured tokens.json ——
const colorBase = pick(base, /^--(orange|periwinkle|ink|slate|gray|white|black|success|warning|danger|info|gradient|glow|bg-|surface|text-|border|accent|chart-|overlay-)/);
const colorDark = pick(dark, /^--(bg-|surface|text-|border|accent|glow|overlay-)/);
const tokens = {
  $meta: { source: "tokens/*.css", note: "Generated by scripts/gen-tokens.mjs — edit the CSS, not this file." },
  color: byName(colorBase),
  colorDark: byName(colorDark),
  fontFamily: byName(pick(base, /^--font-/)),
  fontWeight: byName(pick(base, /^--fw-/)),
  fontSize: byName(pick(base, /^--text-/)),
  lineHeight: byName(pick(base, /^--lh-/)),
  letterSpacing: byName(pick(base, /^--ls-/)),
  spacing: byName(pick(base, /^--space-/)),
  density: byName(pick(base, /^--density-/)),   // `comfortable` defaults; compact/spacious live in tokens/density.css
  radius: byName(pick(base, /^--radius-/)),
  shadow: byName(pick(base, /^--shadow-/)),
  elevation: byName(pick(base, /^--elevation-/)),   // semantic layer over the shadow ramp
  motion: byName(pick(base, /^--(dur|ease)-/)),
  zIndex: byName(pick(base, /^--z-/)),
  opacity: byName(pick(base, /^--opacity-/)),
  breakpoint: Object.fromEntries([...fs.readFileSync(path.join(ROOT, "tokens/spacing.css"), "utf8").matchAll(/--(bp-[a-z]+):\s*([0-9px]+);/g)].map((x) => [x[1], x[2]])),
};
emit("tokens/tokens.json", JSON.stringify(tokens, null, 2));

// —— Tailwind preset (references CSS vars so it tracks the active theme) ——
const varMap = (list, strip) => Object.fromEntries(list.map((t) => {
  const key = t.name.replace(strip, "");
  return [key, `var(${t.name})`];
}));
const colorsTW = varMap(pick(base, /^--(orange|periwinkle|ink|slate|gray|success|warning|danger|info|accent|chart-)/), /^--/);
colorsTW.white = "#FFFFFF"; colorsTW.black = "#000000";
["bg-page", "bg-canvas", "surface-card", "surface-raised", "surface-sunken", "border-subtle", "border-default", "text-primary", "text-secondary", "text-muted"].forEach((n) => { colorsTW[n] = `var(--${n})`; });
const fontFamilyTW = { display: ["var(--font-display)"], sans: ["var(--font-sans)"], accent: ["var(--font-accent)"], inter: ["var(--font-inter)"] };
const fontSizeTW = byName(pick(base, /^--text-/));
const radiusTW = varMap(pick(base, /^--radius-/), /^--radius-/);
const shadowTW = { ...varMap(pick(base, /^--shadow-/), /^--shadow-/), ...varMap(pick(base, /^--elevation-/), /^--/) };
const spacingTW = byName(pick(base, /^--space-/)); // "space-4": "16px" -> key "space-4"
const spacingClean = Object.fromEntries(Object.entries(spacingTW).map(([k, v]) => [k.replace("space-", ""), v]));
const preset = `/* Alfred AI — Tailwind preset. Generated by scripts/gen-tokens.mjs.
   Colors/radius/shadow reference the live CSS custom properties, so utilities
   like bg-orange-500, rounded-2xl and shadow-md track the active theme.
   Load styles.css alongside this preset. */
module.exports = {
  theme: {
    extend: {
      colors: ${JSON.stringify(colorsTW, null, 6).replace(/\n/g, "\n      ")},
      fontFamily: ${JSON.stringify(fontFamilyTW, null, 6).replace(/\n/g, "\n      ")},
      fontSize: ${JSON.stringify(fontSizeTW, null, 6).replace(/\n/g, "\n      ")},
      borderRadius: ${JSON.stringify(radiusTW, null, 6).replace(/\n/g, "\n      ")},
      boxShadow: ${JSON.stringify(shadowTW, null, 6).replace(/\n/g, "\n      ")},
      spacing: ${JSON.stringify(spacingClean, null, 6).replace(/\n/g, "\n      ")},
      zIndex: ${JSON.stringify(varMap(pick(base, /^--z-/), /^--z-/), null, 6).replace(/\n/g, "\n      ")},
      backgroundImage: { "gradient-brand": "var(--gradient-brand)", "gradient-brand-reverse": "var(--gradient-brand-reverse)" },
    },
  },
};
`;
emit("tokens/tailwind.preset.cjs", preset);

// —— Framer color + text styles (name → light/dark hex) ——
const darkByName = byName(colorDark);
const isHexish = (v) => /^(#|rgb|rgba)/.test(v);
const framerColors = colorBase
  .filter((t) => isHexish(t.value))
  .map((t) => {
    const key = t.name.replace(/^--/, "");
    const d = darkByName[key];
    return { name: key, light: t.value, ...(d && isHexish(d) ? { dark: d } : {}) };
  });
const framerText = pick(base, /^--text-(display|h[1-6]|lg|base|sm|xs|2xs)/).map((t) => ({ name: t.name.replace(/^--/, ""), fontSize: t.value, fontFamily: "Satoshi (web) / Clash Display (app headings)" }));
emit("tokens/framer-styles.json", JSON.stringify({ colorStyles: framerColors, textStyles: framerText }, null, 2));

const stale = [];
let written = 0;
for (const [rel, next] of OUT) {
  const abs = path.join(ROOT, rel);
  const prev = fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
  if (prev === next) continue;
  if (CHECK) { stale.push(rel); continue; }
  fs.writeFileSync(abs, next);
  written++;
}
if (CHECK) {
  if (stale.length) {
    console.log(`FAIL stale token exports — run \`node scripts/gen-tokens.mjs\` and commit:\n  ${stale.join("\n  ")}`);
    process.exit(1);
  }
  console.log("OK   tokens      — manifest, tokens.json, Tailwind preset and Framer styles match a clean rebuild");
} else {
  console.log("tokens.json:", Object.keys(tokens.color).length, "colors,", Object.keys(tokens.fontSize).length, "sizes");
  console.log(`${written} of ${OUT.size} token export(s) rewritten (manifest · tokens.json · tailwind preset · framer styles)`);
}
