/* Generate index.html — the design-system landing page — from _ds_manifest.json,
   so it always reflects the current components, preview cards and groups.
   Run: node scripts/gen-index.mjs  (also run by the build flow) */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(new URL("..", import.meta.url).pathname);
const m = JSON.parse(fs.readFileSync(path.join(ROOT, "_ds_manifest.json"), "utf8"));

// Fold the registered templates (deck, sections gallery) in as Template cards.
const templateCards = (m.templates || []).map((t) => ({ path: t.entryPath, group: "Templates", name: t.name, subtitle: t.description }));
const allCards = [...m.cards, ...templateCards];

const compCount = m.components.length;
const cardCount = allCards.length;
const compGroups = [...new Set(m.components.map((c) => c.sourcePath.split("/")[1]))];

// Card group → display order + an icon from assets/icons.
const GROUP_META = {
  "Alfred App": { icon: "cta-arrow", order: 1 },
  Website: { icon: "web-clarity", order: 2 },
  Components: { icon: "web-stack-connected", order: 3 },
  Colors: { icon: "channel-mix", order: 4 },
  Type: { icon: "web-clarity", order: 5 },
  Spacing: { icon: "fullscreen", order: 6 },
  Brand: { icon: "bookmark", order: 7 },
  Templates: { icon: "export", order: 8 },
  Decks: { icon: "demo-play", order: 9 },
  Slides: { icon: "fullscreen", order: 10 },
};
const groups = [...new Set(allCards.map((c) => c.group))]
  .sort((a, b) => (GROUP_META[a]?.order || 99) - (GROUP_META[b]?.order || 99));

const esc = (s) => String(s == null ? "" : s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const cardHtml = (c) => {
  const ic = GROUP_META[c.group]?.icon || "bookmark";
  return `<a class="card" href="${esc(c.path)}"><div class="ic"><span style="-webkit-mask-image:url(assets/icons/${ic}.svg);mask-image:url(assets/icons/${ic}.svg)"></span></div><h3>${esc(c.name)}</h3><p>${esc(c.subtitle || "")}</p></a>`;
};
const sections = groups.map((g) => {
  const cards = allCards.filter((c) => c.group === g).map(cardHtml).join("\n        ");
  return `      <p class="eyebrow">${esc(g)}</p>\n      <div class="grid">\n        ${cards}\n      </div>`;
}).join('\n\n      <div class="gap"></div>\n\n');

const docCards = [
  ["readme.md", "audit-log", "Read the guide", "Voice, visual foundations, iconography and the full file index."],
  ["CHANGELOG.md", "trend-up", "Changelog", "What changed and when — the system's release history."],
  ["CONTRIBUTING.md", "integration-success", "Contributing", "How to add a component, run the verifiers and re-sync."],
  ["tokens/tokens.json", "channel-mix", "Tokens (JSON)", "Structured token export + Tailwind preset + Framer styles."],
].map(([href, ic, t, d]) =>
  `<a class="card" href="${href}"><div class="ic"><span style="-webkit-mask-image:url(assets/icons/${ic}.svg);mask-image:url(assets/icons/${ic}.svg)"></span></div><h3>${t}</h3><p>${d}</p></a>`
).join("\n        ");

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Alfred AI — Design System</title>
<link rel="icon" href="assets/logos/alfred-favicon-black.svg" />
<link rel="stylesheet" href="styles.css" />
<!-- Generated by scripts/gen-index.mjs from _ds_manifest.json — do not edit by hand. -->
<style>
  body { margin: 0; background: var(--bg-canvas); }
  .glow { position: relative; overflow: hidden; background:
    var(--glow-periwinkle), var(--glow-orange), #fff; padding: 80px 56px 56px; }
  .wrap { max-width: 1080px; margin: 0 auto; }
  .logo { height: 40px; margin-bottom: 56px; }
  .hero h1 { font-family: var(--font-display); font-weight: 700; font-size: 72px; line-height: 1.0;
    letter-spacing: -0.03em; margin: 0; max-width: 860px; }
  .hero .em { background: var(--gradient-brand); -webkit-background-clip: text; background-clip: text; color: transparent; }
  .hero p { font-size: 21px; color: var(--text-secondary); margin: 22px 0 0; max-width: 620px; line-height: 1.5; }
  .stats { display: flex; gap: 28px; margin-top: 30px; flex-wrap: wrap; }
  .stat b { font-family: var(--font-display); font-weight: 700; font-size: 30px; color: var(--ink-900); letter-spacing: -0.02em; }
  .stat span { font-family: var(--font-sans); font-size: 14px; color: var(--text-muted); display: block; }
  .body { max-width: 1080px; margin: 0 auto; padding: 48px 56px 96px; }
  .eyebrow { font-family: var(--font-sans); font-size: 12px; font-weight: 700; letter-spacing: var(--ls-caps);
    text-transform: uppercase; color: var(--text-muted); margin: 0 0 18px; }
  .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 18px; }
  .gap { height: 40px; }
  .card { display: flex; flex-direction: column; gap: 10px; background: #fff; border: 1px solid var(--border-subtle);
    border-radius: var(--radius-2xl); padding: 24px; box-shadow: var(--shadow-sm); text-decoration: none;
    transition: transform var(--dur-base) var(--ease-standard), box-shadow var(--dur-base) var(--ease-standard); }
  .card:hover { transform: translateY(-3px); box-shadow: var(--shadow-lg); opacity: 1; }
  .card .ic { width: 44px; height: 44px; border-radius: var(--radius-md); background: var(--orange-50);
    display: flex; align-items: center; justify-content: center; margin-bottom: 6px; }
  .card .ic span { width: 22px; height: 22px; background: var(--orange-500); -webkit-mask-repeat: no-repeat; mask-repeat: no-repeat;
    -webkit-mask-position: center; mask-position: center; -webkit-mask-size: contain; mask-size: contain; }
  .card h3 { font-family: var(--font-display); font-size: 20px; font-weight: 600; color: var(--ink-900); margin: 0; }
  .card p { font-family: var(--font-sans); font-size: 14px; color: var(--text-muted); margin: 0; line-height: 1.5; }
  .sep { height: 1px; background: var(--border-subtle); margin: 44px 0; }
  .swatches { display: flex; gap: 10px; margin-top: 10px; }
  .sw { height: 40px; flex: 1; border-radius: var(--radius-md); }
</style>
</head>
<body>
  <div class="glow">
    <div class="wrap">
      <img class="logo" src="assets/logos/alfred-logo-primary.svg" alt="Alfred ai" />
      <div class="hero">
        <h1>The design system for <span class="em">Alfred ai</span>.</h1>
        <p>Foundations, brand assets, ${compCount} UI components and product kits for Alfred — the decision intelligence platform for marketing leaders.</p>
        <div class="stats">
          <div class="stat"><b>${compCount}</b><span>components · ${compGroups.length} groups</span></div>
          <div class="stat"><b>${cardCount}</b><span>preview cards</span></div>
          <div class="stat"><b>light + dark</b><span>app &amp; marketing themes</span></div>
        </div>
      </div>
    </div>
  </div>

  <div class="body">
${sections}

    <div class="gap"></div>

      <p class="eyebrow">Docs &amp; tokens</p>
      <div class="grid">
        ${docCards}
      </div>

    <div class="sep"></div>

    <p class="eyebrow">The palette</p>
    <div class="swatches">
      <div class="sw" style="background:var(--orange-500)"></div>
      <div class="sw" style="background:var(--periwinkle-400)"></div>
      <div class="sw" style="background:var(--ink-900)"></div>
      <div class="sw" style="background:var(--gradient-brand)"></div>
      <div class="sw" style="background:var(--gray-50); border:1px solid var(--border-subtle)"></div>
    </div>
  </div>
</body>
</html>
`;
fs.writeFileSync(path.join(ROOT, "index.html"), html);
console.log(`index.html generated — ${cardCount} cards across ${groups.length} groups, ${compCount} components.`);
