/* Generate the Inspiration Library's committed artifacts from its meta files.

   Inputs:  library/meta/<category>.json   (hand-authored, one per category)
            library/sections/<category>.jsx (the section components)
   Outputs: library/sections.json          (the app + verifier schema)
            library/export/<id>.html       (static standalone reference of each
                                            section's default variant, dark)

   Both outputs are COMMITTED and freshness-gated by verify-library.mjs, the
   same deterministic-rebuild contract as props.json and the kit twins: a meta
   or section edit that is not regenerated fails CI.

   Run: node scripts/gen-library.mjs   (--check to diff without writing) */
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { TextEncoder, TextDecoder } from "node:util";

const ROOT = path.resolve(new URL("..", import.meta.url).pathname);
const read = (f) => fs.readFileSync(path.join(ROOT, f), "utf8");
const dep = (f) => fs.readFileSync(path.join(ROOT, "node_modules", f), "utf8");

export function readMetas() {
  const dir = path.join(ROOT, "library/meta");
  const files = fs.readdirSync(dir).filter((f) => f.endsWith(".json")).sort();
  const metas = files.map((f) => {
    const m = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
    m.__file = "library/meta/" + f;
    return m;
  });
  metas.sort((a, b) => (a.category.order ?? 99) - (b.category.order ?? 99));
  return metas;
}

export function readRecipes() {
  const dir = path.join(ROOT, "library/recipes");
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((f) => f.endsWith(".html")).sort().map((f) => {
    const head = fs.readFileSync(path.join(dir, f), "utf8").split("\n", 1)[0];
    const attr = (k) => (head.match(new RegExp(`${k}="([^"]*)"`)) || [])[1] || null;
    return { slug: f.replace(/\.html$/, ""), name: attr("name"), subtitle: attr("subtitle") };
  });
}

export function readStyles() {
  const dir = path.join(ROOT, "library/styles");
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter((f) => f.endsWith(".html") && f !== "index.html").sort()
    .map((f) => {
      const head = fs.readFileSync(path.join(dir, f), "utf8").split("\n", 1)[0];
      const name = (head.match(/Style exploration:\s*([^.]+)\./) || [])[1] || null;
      return { slug: f.replace(/\.html$/, ""), name };
    });
}

export function buildSectionsJson(metas) {
  return JSON.stringify({
    generatedBy: "scripts/gen-library.mjs",
    categories: metas.map((m) => ({ ...m.category, count: m.sections.length })),
    sections: metas.flatMap((m) => m.sections.map((s) => ({ category: m.category.id, ...s }))),
    recipes: readRecipes(),
    styles: readStyles(),
  }, null, 2) + "\n";
}

/* —— SSR harness, same vm technique as verify-render.mjs ——————————— */
let ssr = null;
export function ssrHarness() {
  if (ssr) return ssr;
  const warnings = [];
  const mkdoc = () => new Proxy(function () {}, { get: () => mkdoc(), apply: () => mkdoc() });
  const ctx = {
    console: { ...console, error: (...a) => warnings.push(String(a[0])), warn: (...a) => warnings.push(String(a[0])) },
    setTimeout, clearTimeout, queueMicrotask, TextEncoder, TextDecoder, ReadableStream,
    MessageChannel: class { constructor() { this.port1 = { postMessage() {}, close() {} }; this.port2 = { postMessage() {}, close() {} }; } },
  };
  ctx.window = ctx; ctx.self = ctx; ctx.globalThis = ctx; ctx.document = mkdoc(); ctx.navigator = { userAgent: "node" };
  vm.createContext(ctx);
  const exec = (code, name) => vm.runInContext(code, ctx, { filename: name });
  exec(dep("react/umd/react.development.js"), "react.js");
  exec(dep("react-dom/umd/react-dom-server.browser.development.js"), "server.js");
  exec(dep("@babel/standalone/babel.min.js"), "babel.js");
  exec(read("_ds_bundle.js"), "_ds_bundle.js");
  const loaded = new Set();
  const loadJsx = (f) => {
    if (loaded.has(f)) return;
    loaded.add(f);
    exec("(function(){\n" + ctx.Babel.transform(read(f), { presets: ["react"], filename: f }).code + "\n})()", f);
  };
  const render = async (globalName, props) => {
    warnings.length = 0;
    const Comp = ctx[globalName];
    if (typeof Comp !== "function") throw new Error(globalName + " not exported on window");
    const errs = [];
    const stream = await ctx.ReactDOMServer.renderToReadableStream(
      ctx.React.createElement(Comp, props), { onError: (e) => errs.push(e.message) });
    const html = await new Response(stream).text();
    const warn = warnings.filter((w) => /Warning:/.test(w));
    if (errs.length || warn.length) throw new Error((errs[0] || warn[0]).split("\n")[0]);
    return html;
  };
  ssr = { loadJsx, render, ctx };
  return ssr;
}

const shell = (section, markup) => `<!-- GENERATED by scripts/gen-library.mjs from ${section.file.replace(/\.js$/, ".jsx")} + library/meta — do not edit.
     Static reference render of "${section.name}" (${section.id}), default variant, marketing dark.
     Interactive behaviour (accordions, forms) is inert here; open the library app for the live version. -->
<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Alfred library — ${section.name}</title>
<link rel="stylesheet" href="../../styles.css" />
<style>html, body { margin: 0; } body { background: var(--bg-page); }</style>
</head>
<body>
${markup}
</body>
</html>
`;

export async function buildArtifacts() {
  const metas = readMetas();
  const files = new Map();
  files.set("library/sections.json", buildSectionsJson(metas));
  const h = ssrHarness();
  for (const m of metas) {
    for (const s of m.sections) {
      h.loadJsx(s.file.replace(/\.js$/, ".jsx"));
      const props = (s.variants && s.variants[0] && s.variants[0].props) || {};
      const markup = await h.render(s.global, props);
      files.set("library/export/" + s.id + ".html", shell(s, markup));
    }
  }
  return files;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === new URL(import.meta.url).pathname;
if (isMain) {
  const CHECK = process.argv.includes("--check");
  const files = await buildArtifacts();
  fs.mkdirSync(path.join(ROOT, "library/export"), { recursive: true });
  const stale = [];
  let written = 0;
  for (const [rel, next] of files) {
    const abs = path.join(ROOT, rel);
    const prev = fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
    if (prev === next) continue;
    if (CHECK) { stale.push(rel); continue; }
    fs.writeFileSync(abs, next);
    written++;
  }
  /* an export whose section no longer exists must not linger */
  const expected = new Set([...files.keys()].filter((f) => f.startsWith("library/export/")).map((f) => path.basename(f)));
  const exportDir = path.join(ROOT, "library/export");
  for (const f of fs.existsSync(exportDir) ? fs.readdirSync(exportDir) : []) {
    if (f.endsWith(".html") && !expected.has(f)) {
      if (CHECK) stale.push("library/export/" + f + " (orphan)");
      else { fs.unlinkSync(path.join(exportDir, f)); written++; }
    }
  }
  if (CHECK) {
    if (stale.length) {
      console.log(`FAIL stale library artifacts — run \`node scripts/gen-library.mjs\` and commit:\n  ${stale.join("\n  ")}`);
      process.exit(1);
    }
    console.log("OK   library     — sections.json and export/ match a clean rebuild");
  } else {
    console.log(`Library: ${written} file(s) written of ${files.size} generated.`);
  }
}
