/* GENERATED by scripts/build-kits.mjs from ui_kits/website/boot.jsx — do not edit. */
(function () {
function Site() {
  return /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement(window.SiteNav, null), /*#__PURE__*/React.createElement(window.Hero, null), /*#__PURE__*/React.createElement(window.AlfredCore, null), /*#__PURE__*/React.createElement(window.Products, null), /*#__PURE__*/React.createElement(window.HowItWorks, null), /*#__PURE__*/React.createElement(window.Outcomes, null), /*#__PURE__*/React.createElement(window.Security, null), /*#__PURE__*/React.createElement(window.Faq, null), /*#__PURE__*/React.createElement(window.CTA, null), /*#__PURE__*/React.createElement(window.SiteFooter, null));
}
ReactDOM.createRoot(document.getElementById("root")).render(/*#__PURE__*/React.createElement(Site, null));

/* function declarations, global as they were under the browser compiler */
window.Site = Site;
})();
